### ISSUE TITLE
Unbounded height error in DataTable2

### ISSUE THREAD

**Issue by DeepBhat** [maxim-saplin/data_table_2#104]
Wrapping the table in a column is giving me an unbounded height exception. Is this expected behavior or am I doing something wrong? I have tried specifying the height of each row, all Columns have main axis size set to `MainAxisSize.min`, there are no `SingleChildScrollView` parents to this widget. I don't know what to do.
Here is my table:
```
class ArticleDistributionTable extends ConsumerStatefulWidget {
  const ArticleDistributionTable({Key? key, required this.article})
      : super(key: key);
  final Article article;

  @override
  ConsumerState<ConsumerStatefulWidget> createState() =>
      _ArticleDistributionTableState();
}

class _ArticleDistributionTableState
    extends ConsumerState<ArticleDistributionTable> {
  int _currentSortColumn = 0;
  bool _isAscending = true;

  @override
  Widget build(BuildContext context) {
    return DataTable2(
      sortColumnIndex: _currentSortColumn,
      sortAscending: _isAscending,
      minWidth: 600,
      columns: widget.article
          .getColumnNames()
          .map(
            (name) => DataColumn2(
                label: Text(name),
                onSort: (columnIndex, _) {
                  setState(() {
                    _currentSortColumn = columnIndex;
                    if (_isAscending == true) {
                      _isAscending = false;
                      widget.article.distribution.sort((a, b) => a
                          .getColumnValue(name)
                          .compareTo(b.getColumnValue(name)));
                    } else {
                      _isAscending = true;
                      widget.article.distribution.sort((a, b) => b
                          .getColumnValue(name)
                          .compareTo(a.getColumnValue(name)));
                    }
                  });
                }),
          )
          .toList(),
      rows: widget.article.distribution
          .map(
            (distribution) => DataRow2(
              cells: <DataCell>[
                DataCell(Text(distribution.color)),
                DataCell(Text(distribution.location)),
                ...distribution.sizeDistribution.values
                    .map((value) => DataCell(Text(value.toInt().toString())))
              ],
            ),
          )
          .toList(),
    );
  }
}
```

**Comment by maxim-saplin** [comment]
You shouldn't be putting it into Column  if for some reasons this is required, try wrapping DataTable2 into Expanded or Flexible

**Comment by gslender** [comment]
Just so you know, the original DataTable works fine in unbounded containers, so your widget isn't 100% correctly a drop in replacement for Flutter's DataTable (as you outline in your readme page) - maybe think about adding the point, that unlike the Flutter DataTable (which is based on Table, which sizes itself based on the rows/columns etc), DataTable2 will require a correctly sized container to render into. Fair?

**Comment by maxim-saplin** [comment]
That's right, I've added that point to Readme

**Comment by abdimussa87** [comment]
What if I wanted to use it inside a list view?

**Comment by maxim-saplin** [comment]
Then you would have to put the table inside a SizedBox() and put a height constraint.

Though there's a question why do so. If you would like to put the table in the list view as a single widget -> IMO that doesn't make any sense. If the table will be one of few widgets inside a scrollable list, having bounded height might work, though I am not sure how nested scrolling will behave, there might be surprises

**Comment by abdimussa87** [comment]
Yeah, you are right. Thanks for your response
