### ISSUE TITLE
Add scrollPhysics for vertical and horizontal

### ISSUE THREAD

**Issue by lordvidex** [maxim-saplin/data_table_2#107]
ScrollPhysics helps when table is nested in a sliver but is unfortunately not available from the parameters.

**Comment by maxim-saplin** [comment]
If you're talking of overriding scroll physics for the scrollable inside data table widgets, I believe that can be done via Flutter's standard capabilities: https://stackoverflow.com/questions/62809540/how-can-you-change-the-default-scrollphysics-in-flutter
