### ISSUE TITLE
When loading AsyncPaginatedDataTable2, the DataColumn style is displayed abnormally

### ISSUE THREAD

**Issue by javaqiang** [maxim-saplin/data_table_2#108]
![image](https://user-images.githubusercontent.com/3114560/175454486-3c42bdb9-f8e5-4e36-81ab-8055c3afa562.png)
When loading AsyncPaginatedDataTable2, the DataColumn style is displayed abnormally，there is no table line, and the width is squeezed.
This problem does not exist in version V2.2.3

**Comment by maxim-saplin** [comment]
Hi!

Do you mean that when loading there're no borders in the header while they appear after the loading is complete?

And I believe the second discrepancy you mention is column width is changed after the loading is complete.

Thanks for creating the issue, you did find tricky defects I wouldn't pay attention to!

**Comment by javaqiang** [comment]
Yes, you're quite right.
Thank you for providing data_table_2, it works great, 
looking forward to the new version with the fix.

**Comment by maxim-saplin** [comment]
Fixed and pushed to pub.dev(2.3.3)
