### ISSUE TITLE
Fixed rows / columns issues

### ISSUE THREAD

**Issue by Govindbetterlives** [maxim-saplin/data_table_2#109]
Hi,

I am using Data Table 2: 2.1.1 version. Can you guide me on how to set up fixed rows and columns(paginated datatable) in this version?. Because I have customized the code according to my design.

**Comment by maxim-saplin** [comment]
Fixed (left) columns are not available in versions prior to 2.3.0. Use the most recent one (today it is 2.3.3). You can check the examples folder and run them, there's one page devoted to demonstrating fixed rows/columns
