### ISSUE TITLE
The checkbox cell position doesn't align with other cells in the same row

### ISSUE THREAD

**Issue by TinhHuynh** [maxim-saplin/data_table_2#111]
Hi, I am building an application showing data in the data table and allowing users to toggle select mode.
There is a problem that, when I scroll down the data table a little bit and then toggle the showCheckMode mode, the column of checkboxes doesn't align with other cells in the same row. However, when I scroll again and the problem disappears.

Please see the attached video for reference. Thanks

https://user-images.githubusercontent.com/21233282/176119279-f5ece972-164f-42ab-9990-93c78e86f785.mp4

**Comment by TinhHuynh** [comment]
Hi, it happens when I set fixedLeftColumns = 1, when I set it to zero then it is fine. I read the source code that fixedLeftColumns is a separate table, so that's why when enabling it will cause the problem?

**Comment by maxim-saplin** [comment]
Good catch, I guess I have a suspect, will check latter today/tomorrow

**Comment by maxim-saplin** [comment]
I've pushed the fix to main, could you please try referencing the package directly from pub.dev:

```
dependencies:
  data_table_2:
    git: https://github.com/maxim-saplin/data_table_2
```

**Comment by TinhHuynh** [comment]
Hi, thanks for your work and time.
I pointed the library to the git URL as you said and it works fines. 
However, there is a very short scroll animation at the start.
Please see the attached video.
https://user-images.githubusercontent.com/21233282/176331687-f35290d0-2da2-46f8-b660-1edaeb597d8d.mp4

**Comment by maxim-saplin** [comment]
Indeed, that's an artefact related to implementation detail. To avoid you can use ScrollClontroller() (stored in state or in static field) which can be passed to the widget, that will allow to avoid the trouble:

```
DataTable2(
                      scrollController: _controller,
```

**Comment by maxim-saplin** [comment]
Pushed to pub.dev
