### ISSUE TITLE
Ellipses for truncated column text?

### ISSUE THREAD

**Issue by hootyjeremy** [maxim-saplin/data_table_2#112]
I don't know if this is an issue or not but I don't know where to ask questions, really. Is it possible to show ellipses on text that is truncated when it is larger than the column width?

**Comment by maxim-saplin** [comment]
That's easy. Use overflow property of Text() widget. E.g., ellipses in header:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/7947027/176358494-e0360f63-2887-469a-9673-3409a5c9b010.png">

and cell:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/7947027/176358573-7dfc4b25-38b0-4f2a-950c-e1a3db74e07e.png">

That's the result:

<img width="269" alt="image" src="https://user-images.githubusercontent.com/7947027/176358399-43bed666-6f2b-45e8-aca5-6485e3e7d3e5.png">

**Comment by hootyjeremy** [comment]
I have not yet come across TextOverflow. Thanks a lot. :D
