### ISSUE TITLE
Sliding to the boundary, unable to swipe in the rebound

### ISSUE THREAD

**Issue by smartsimba** [maxim-saplin/data_table_2#113]
Sliding to the boundary, there will be a rebound effect. During the rebound process, you cannot slide up, down, left and right. During the rebound process, the characters will also shake, I hope to cancel the rebound effect, thank you.
code version: 2.3.3
device: iphoneX, 15.4.

https://user-images.githubusercontent.com/11230335/176386744-2a19fb00-3d26-45f0-8968-bde3e4eefd9b.mp4

1

**Comment by maxim-saplin** [comment]
Thanks, will check what can be done to fix the issue

**Comment by maxim-saplin** [comment]
Fixed and pushed to pub.dev. Though there's a side effect (bug or feature, not sure), when bouncing parts go out of sync
