### ISSUE TITLE
Is it possible to resize columns?

### ISSUE THREAD

**Issue by hootyjeremy** [maxim-saplin/data_table_2#114]
I'm trying to basically recreate an Explorer window's "Details" view of files with their details in columns. I'd like to be able to let the user resize the columns to whatever widths they like (and I'll store that value for persistence). I don't know if this is addressed somewhere else and I'm just not seeing it. 

Thanks.

**Comment by maxim-saplin** [comment]
There's no such feature in the stable version of the widget. Though there's a WIP PR with exactly that capability. So far no ETA on the completion, you can play with the PR branch if you wish: https://github.com/maxim-saplin/data_table_2/pull/93
