### ISSUE TITLE
[Enhancemet] Select columns or rows to make them fixed rows/colums

### ISSUE THREAD

**Issue by dthuesen** [maxim-saplin/data_table_2#115]
Use case: A user wants to compare data from one or more rows/columns with the rest of the data in the table without having to always scroll back and forth between the camparable base and the rest.

**Comment by maxim-saplin** [comment]
That feature is easily implementable with the current `DataTable2` widget. If certain row to be selected and fixed, in the event handler you'll have to rearrange data rows and put the selected row to the top, also increment `fixedTopRow` property of the DataTable2. Same goes for the columns -> you reorder data columns and increment `fixedLeftCoumns`

I don't think there's room for that kind of logic in `DataTable2`, there's one way data flow, the widget receives rows/column externally and displays them as requested.
