### ISSUE TITLE
Allow flex or size in DataColumn

### ISSUE THREAD

**Issue by deadsoul44** [maxim-saplin/data_table_2#12]
Hello,

Specifying enum is not enough to size the column width. For example, I want the first column to be larger than `ColumnSize.L` and the remaining columns to be smaller than `ColumnSize.S`. It could be great to either expose the values of these enum ratios or allow to specify flex value. If you allow flex, you can refactor `minWidth` to `width` which will be horizontal width of the table.

Thank you for the great package.

**Comment by maxim-saplin** [comment]
Hi, you can override the ratios via `void setColumnSizeRatios(double sm, double lm)` - I hope that sufices

**Comment by deadsoul44** [comment]
It is working, thank you very much but it could be better to have these as parameters in DataTable2.

**Comment by maxim-saplin** [comment]
Agreed regarding params, it might be better to have the ratios as constuctor params with default values. Will look into that

**Comment by maxim-saplin** [comment]
2.0.4 version is now publishde and has the change

**Comment by deadsoul44** [comment]
Thank you. I will try it.

**Comment by erufenix** [comment]
Code example please?

**Comment by maxim-saplin** [comment]
Which example do you want to see?
