### ISSUE TITLE
Add horizontalScrollController to widgets

### ISSUE THREAD

**Issue by blueeyestw** [maxim-saplin/data_table_2#124]
When trying to call any function with the scroll controller, nothing happens.
I have tried with `animateTo` ,`jumpTo`, and `addListener`.
None of them seems to work.

Minimum reproducible code:
```
import 'package:data_table_2/data_table_2.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late ScrollController scrollController;
  @override
  void initState() {
    scrollController = ScrollController();
    super.initState();
  }

  @override
  void dispose() {
    scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: DataTable2(
          minWidth: 30 * 40,
          horizontalMargin: 16.0,
          columnSpacing: 8.0,
          scrollController: scrollController,
          columns: [
            for (int c = 1; c <= 30; c++)
              DataColumn2(label: Text(c.toString())),
          ],
          rows: [
            for (int r = 1; r <= 10; r++)
              DataRow2(
                onTap: () => scrollController.jumpTo(0.0), //tapping any row should jump back to the start *NOT WORKING*
                cells: [
                  for (int c = 1; c <= 30; c++)
                    DataCell(SizedBox(width: 40.0, child: Text('${c * r}'))),
                ],
              ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by maxim-saplin** [comment]
The scroll controller only works with vertical direction, and it was always the case... Though it seems I've made a silly mistake in the inline docs stating that it controls horizontal direction...

<img width="576" alt="image" src="https://user-images.githubusercontent.com/7947027/180851058-d65519ca-305b-40be-98bc-1cf83142cbf5.png">

Vertical scrolling works fine on my end. Is that the case for you as well?

**Comment by blueeyestw** [comment]
Thank you for the quick response. I was indeed confused by the documentation. Vertical scrolling is working fine, is there a way to control horizontal scrolling?

**Comment by maxim-saplin** [comment]
There's no such feature in the moment, will keep the issue to keep track of it

**Comment by martinpelli** [comment]
Hi @maxim-saplin I need a controller for the horizontal axis, If I modify the package I will able to do that? I mean is like finding the scrollable Widget and adding the scroll controller or it's more difficult than that? I only touched a package once in my life and was for changing colors so I am like a newbie for modifyng/doing packages

**Comment by maxim-saplin** [comment]
There're 4 controller under the hood, 2 for each direction which are synced to ensure scrolling of fixed parts. There's already vertical controller exposed which is essentially one of the 2 synced controller. I would say it is an easy task, Medium complexity) Though messing with synced controllers might be tricky. Event having created the code personally I wouldn't say I completely understand how they work)

**Comment by martinpelli** [comment]
thanks sr! I will try

**Comment by martinpelli** [comment]
@maxim-saplin  Okay, I was able to do it and it's working, I just copied logic from sc11 to sc21, renamed scrollController to verticalScrollController and added horizontalScrollController. I don't know if you want a pr.

**Comment by maxim-saplin** [comment]
Wrapping it in A PR would be great. Though could you please check the existing tests pass, add an new test for the change and document the property exposed

**Comment by martinpelli** [comment]
> Wrapping it in A PR would be great. Though could you please check the existing tests pass, add a new test for the change and document the property exposed

All test should be ok? I am getting this 
![image](https://user-images.githubusercontent.com/63437171/226198680-6dea95ac-f784-4b9b-8c4d-9da86c46db62.png)

**Comment by maxim-saplin** [comment]
Golden tests might fail. Expand and have a look which ones fail

**Comment by martinpelli** [comment]
yes, they are all golden, okay didn't know about golden tests.

**Comment by martinpelli** [comment]
So the only thing left are tests.
![image](https://user-images.githubusercontent.com/63437171/226203364-940397a3-b8eb-4011-86cc-57d9685e9718.png)
Here, I understand that you are testing that KitKat cell is not clickleable until you scroll to 10000 and then it has to be clickleable. But I don't get How you know that you have to jump to 10000 and how you know KitKat is a cell. How I can see the table built here? I mean, the view, if I run the main.dart from Example folder there is no KitKat. So I need to figure out to which point scroll the horizontal controller and which cell will be visible

**Comment by maxim-saplin** [comment]
10000 is just a number large enough to get the widget scrolled ot to the very end. The actual scroll offset is apparently different, Flutter caps it to max offset available. 

build Table is where you get the widget to be tested, /example is of no relevance here.

**Comment by martinpelli** [comment]
I uderstand that,  what I don't understand is that with this data 

![image](https://user-images.githubusercontent.com/63437171/226492523-6f891082-6b0e-424f-8914-168a45b11080.png)

 How I can know the number to so that when scrolling horizontally the widget scrolls to the end? Putting 10000 like in the image is causing an exeption

**Comment by martinpelli** [comment]
Yes I know that, What I mean is that how you know the DataTable2 is scrollable horizontally if there is no view to watch.
Considering this data is for testing: 
![image](https://user-images.githubusercontent.com/63437171/226494379-989885cb-6631-4c85-84f1-245291a5926e.png)

Frozen Yogurt has to be visible at start, but when scrolling (I don't know the widget width to know if is scrollable, but just in case I wrapped it in a small width SizedBox)  Shouldn't be visible and still is finding it, so I am doing somentihg wrong with the test.

![image](https://user-images.githubusercontent.com/63437171/226494603-8e3a9fea-0b7e-4219-b4cc-c7c86d6770cd.png)

![image](https://user-images.githubusercontent.com/63437171/226494623-249081a5-18fe-4f25-931f-9dec2ac4c503.png)

**Comment by maxim-saplin** [comment]
You can use DataColum2.fixedWidth (https://pub.dev/documentation/data_table_2/latest/data_table_2/DataColumn2/fixedWidth.html) to define each individual column width, this way you'll know what is the total width of the table. Then with wrapWidgetSetSurf you can define the viewport size and make sure you have it narrow enough to make a certain columns move out of viewport when scrolled

**Comment by maxim-saplin** [comment]
The frature has been implemented and published quite a while ago
