### ISSUE TITLE
Show checkbox column after long press on any row

### ISSUE THREAD

**Issue by mohammedX6** [maxim-saplin/data_table_2#125]
Is the library support this feature?

**Comment by maxim-saplin** [comment]
There're all the required pieces to make that happen:
1. There's showCheckBoxColumn property in table widgets
2. DataRow has onLongPress event

All you need is to put the table inside a stateful widget, declare event handler for long press event and assign it to all rows, in the handler do setState() and set a bool flag which is used build() to define value for showCheckBoxColumn

**Comment by mohammedX6** [comment]
That's Great! Thanks.
