### ISSUE TITLE
Is it already possible to do column header dividers?

### ISSUE THREAD

**Issue by hootyjeremy** [maxim-saplin/data_table_2#127]
I see that there is a `border` parameter that can draw borders around and within the table but is it possible to just create column header dividers instead to look like this? Here's an example of what I've worked on so far but will not create a PR if this can already be done.

![image](https://user-images.githubusercontent.com/68588318/182928309-bd7e3ea6-d73e-48bb-8b68-1cd7415ed5cd.png)

**Comment by hootyjeremy** [comment]
Also, I'm not sure yet why the borders I've drawn here seem to have different thicknesses when using the same border widget.

**Comment by maxim-saplin** [comment]
Border's are tricky, assuming the internal structure of data_table_2:
![image](https://user-images.githubusercontent.com/7947027/183009974-b8f7be87-412a-40db-909d-3faf25b2d22d.png)

Each table is rendered using 1 to 4 separate Table widgets (which are wrapped into scrollables) - that's how fixed headers and footers work. There're 4 sections:
1. Table core - that is the piece which contains non fixed part
2. Fixed top rows
3. Fixed left columns
4. Fixed corner (that's when both fixed top rows and left columns are present)

That means that vertical dividers from the header alone can be present in any of the 4 internal tables. Current implementation of `border` assumes no difference between kinds of rows/columns.

If you can achieve vertical dividers without changing the internals of the widget - that would seems a better option then trying to redesign how dividers can fit internal structure of table. 

Btw, how did you draw those dividers in the header?

**Comment by hootyjeremy** [comment]
So far, I am just adding a BoxDecoration in DataTable2's _buildHeadingCell widget...

`  Widget _buildHeadingCell(
      {required BuildContext context,
      required EdgeInsetsGeometry padding,
      required Widget label,
      required String? tooltip,
      required bool numeric,
      required VoidCallback? onSort,
      required bool sorted,
      required bool ascending,
      required double effectiveHeadingRowHeight,
      required MaterialStateProperty<Color?>? overlayColor,
      Color? backgroundColor}) {
    final ThemeData themeData = Theme.of(context);
    label = Row(
      textDirection: numeric ? TextDirection.rtl : null,
      children: <Widget>[
        Flexible(child: label),
        if (onSort != null) ...<Widget>[
          _SortArrow(
            visible: sorted,
            up: sorted ? ascending : null,
            duration: sortArrowAnimationDuration,
            sortArrowIcon: sortArrowIcon,
          ),
          const SizedBox(width: _sortArrowPadding),
        ],
      ],
    );

    final TextStyle effectiveHeadingTextStyle = headingTextStyle ??
        themeData.dataTableTheme.headingTextStyle ??
        themeData.textTheme.subtitle2!;

    label = Container(
      //decoration: columnHeaderDivider,
      // Add divider to header cell...
      decoration: const BoxDecoration(
        border: Border(
          right: BorderSide(width: 1.0, color: Color(0xffAAAAAA)),
        ),
      ),
      padding: padding,
      height: effectiveHeadingRowHeight,
      color: backgroundColor,
      alignment:
          numeric ? Alignment.centerRight : AlignmentDirectional.centerStart,
      child: AnimatedDefaultTextStyle(
        style: effectiveHeadingTextStyle,
        softWrap: false,
        duration: sortArrowAnimationDuration,
        child: label,
      ),
    );
    if (tooltip != null) {
      label = Tooltip(
        message: tooltip,
        child: label,
      );
    }

    label = InkWell(
      onTap: onSort,
      overlayColor: overlayColor,
      child: label,
    );
    return label;
  }`
  
  I will clean it up and add it as a parameter. I've only done this so far.

**Comment by hootyjeremy** [comment]
I have a fork that I believe achieves the result I was looking for: https://github.com/hootyjeremy/data_table_2

I haven't created a PR yet or set up the tests. I was wondering if you had any input about what I've done so far with this. It works in the examples and also my own example project...

![image](https://user-images.githubusercontent.com/68588318/183272407-a44984d0-96de-4bfb-bde9-501110e01fb4.png)

Would you like me to try setting up tests and do a PR from this?

**Comment by maxim-saplin** [comment]
Might be a good addition. Though what concerns me is that adding header dividers as a separate property might solve little problems while present more confusion.

At the time there're 2 properties which control border outlook: dividerThickness and border. The first create horizontal borders for data cels, the latter controller the border despite the kind of row (header or row) or it's fixed status.

I think the whole approach to managing borders requires a good deal of designing and making it more potent. Adding yet another property and piling up them might be a worng path.

What do you think?

**Comment by hootyjeremy** [comment]
I believe it could be too complicated but I was also thinking of making it mutually exclusive so that if you do use 'border' (which makes it look like a spreadsheet) then the columnHeaderDivider would be ignored. It's actually a specific piece of functionality that I wanted for my own tastes so that it looks similar to a File Explorer's header:

![image](https://user-images.githubusercontent.com/68588318/183318480-ebf74f57-fadf-4f47-887e-a51bdd813864.png)

I believe it's possible that what I've added could introduce problems that I'm not yet aware of but I feel that way about anything I add to anything. To reduce confusion, I did want to make the properties' names very specific and also document in the comments what they are for. 

My personal use for a grid style Widget is to basically emulate a File Explorer window for Desktop apps which I would agree is outside the scope of DataTable and DataTable2. I intend to be working with files in my own app.

**Comment by maxim-saplin** [comment]
I can imagine a number of cases for borders:
- I want vertical dividers in header only
- I want vertical dividers in header and data cells
- I want vertical dividers bold and black in header cells and thin and grey in data cells
- I want to have bold vertical border splitting the fixed column and bold horizontal border splitting fixed top row
- and many more.

Same kind of features might be related to row/cols backgrounds.

There're currently 2 attributes which solve 2 distinct scenarios - horizontal divider for data cells and setting borders for all cells regardless of their kind (is is a fixed column/row cell, is it header etc.). And there's already an interdependency between the 2 items (i.e. when border is set the divider is ignored).

What you suggest is adding yet another property to deal with your specific case and introduce yet another dependency complicating matters further. Yet I don't think that this kind of feature will benefit that many people.

At this point, after introducing the `border` property (and spending a lot of time implementing, fixing and then covering with tests) I wouldn't follow that path - there're 2 many cases solving one specific case, yet another property will bloat the API and worsen the package.

Introducing a more flexible and general approach to managing borders and backgrounds might be the way to go, though I don't have a clear idea of how it might look like.

One of the ideas is having some callback, e.g. cellStyleBuilder, which will be called for every cell, pass in cell info (e.g. it's location, associated columns/row, if it is in the fixed section, header or data portion of the table etc.) and return certain border style or background colour. There can be a set of predefined callbacks, e.g. the one for vertical borders in header.
