### ISSUE TITLE
How to add interior borders/column separators?

### ISSUE THREAD

**Issue by Scylla2020** [maxim-saplin/data_table_2#13]
I cant figure out how to add vertical dividers for the columns please assist

**Comment by maxim-saplin** [comment]
Hi, I beleive you'd like to get smth like that:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/7947027/122170198-f7026180-ce86-11eb-8734-8317b481bcb0.png">
'- there's currently no API exposed that allows to add inner borders. 
 
There're 2 options:
1. Wait for a few days for me to add and publish the feature.
2. Do a quick workaround by copying plugins sorces to you projects folder and making an ad-hoc fix there (lib/data_table2.dart - add `border` property):

```
      var dataRows = Table(
        columnWidths: widthsAsMap,
        children: tableRows,
        border: TableBorder(verticalInside: BorderSide(color: Colors.grey)),
      );
```
```
      var t = Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Table(
              columnWidths: widthsAsMap,
              children: [headingRow],
              border:
                  TableBorder(verticalInside: BorderSide(color: Colors.grey))),

```

**Comment by maxim-saplin** [comment]
Btw, there's an issue in Flutter's repo requesting the same API to be exposed: https://github.com/flutter/flutter/issues/36837

**Comment by Scylla2020** [comment]
Thanks for that. Looking forward to the update! I saw the request on Flutter but seems nothings happened yet

**Comment by maxim-saplin** [comment]
2.0.4 has the feature, sorry for taking a bot longer than promised to publish the update

**Comment by Scylla2020** [comment]
That was quick! Amazing thanks mate! I'll be using it
