### ISSUE TITLE
Remove the highlighted color for a row when double tapped

### ISSUE THREAD

**Issue by softlore** [maxim-saplin/data_table_2#130]
### Versions
| packages/framework | version |
| ----------------------- | -------- |
| flutter                         | 3.0.5 channel_stable |
| data_table_2              |  2.3.6    |
| windows                    | 11         |

### Issue

I am developing a windows app using data_table_2. When a user double clicks on a row, a different screen will be displayed. After user finishes with the 2nd screen and comes back to first screen, the double clicked row is still highlighted

#### Video

https://user-images.githubusercontent.com/19410041/185779680-1d9d6c35-aa4a-4129-9d6f-0b67a12d20ed.mp4

For example,
- user clicked on **Alex** row
- row got highlighted and a second screen is displayed
- user finishes with 2nd screen and comes back to 1st screen
- **Alex** rows is still highlighted
- now he repeats the same with **Charlie**
- both rows are highlighted now

Sample Code:

```dart
import 'package:data_table_2/data_table_2.dart';
import 'package:flutter/material.dart';

class AppExample extends StatefulWidget {
  @override
  State<AppExample> createState() => _AppExampleState();
}

class _AppExampleState extends State<AppExample> {
  buildRows(List<String> data) {
    return DataRow2(
        onDoubleTap: () {
          Navigator.pushNamed(context, '/viewer', arguments: data[0]);
        },
        cells: [data[0], data[1], data[2]].map((e) => DataCell(Text(e))).toList());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: DataTable2(columns: ['Name', 'Age', 'Occupation'].map((e) => DataColumn2(label: Text(e))).toList(), rows: [
      buildRows(['Alex', '24', 'UI/UX']),
      buildRows(['Bob', '27', 'UI/UX']),
      buildRows(['Charlie', '32', 'UI/UX']),
      buildRows(['David', '18', 'UI/UX']),
    ]));
  }
}

class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var args = ModalRoute.of(context)?.settings.arguments as String;
    return Scaffold(
      appBar: AppBar(),
      body: Text(args),
    );
  }
}

void main(List<String> args) {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: '/',
      routes: {'/': (_) => AppExample(), '/viewer': (_) => SecondPage()},
    );
  }
}
```
Please fix the highlight issue.

**Comment by maxim-saplin** [comment]
Could you please elaborate...

 1. Video with the issues
 2. Minimal reproducible example
 - If you can reproduce the issue via the /examples provided with the package -> please described the steps
 - Or submit a sample repo with the case demonstrated

**Comment by softlore** [comment]
Please find the sample code and video in my  original question

**Comment by maxim-saplin** [comment]
Thanks for the update... Here's a workaround you can try:

```
class _AppExampleState extends State<AppExample> {
  buildRows(List<String> data) {
    return DataRow2(
        onDoubleTap: () {
-->    setState(() {});
          Navigator.pushNamed(context, '/viewer', arguments: data[0]);
```

Try adding `setState(() {});` to the tap event.

The cause of the issue is that interbally data table uses TableRowInkWell/InkResponse widgets which change row background and play splash animation on tap. Internally they rely on a stateful widget `_InkResponseStateWidget` which get's stuck in pressed state when navigator pushes a new route. Clicking the back button (effectively calling Navigator.pop) doesn't rebuild the table when returning to home route -> hence the row with invalid background. Calling setState() in the navigation callback ensures the home widget is rebuilt and table row is not stuck in the pressed state.

The root cause of the issue is in the SDK. I'll see to creating a minimal repro cases and submitting an issue to Flutter team. Keeping the issues open

**Comment by maxim-saplin** [comment]
I've submitted an issue to Flutter repo, it seems the fix is already in place, awaiting for it to be pushed to Stable to have data table fixed.

https://github.com/flutter/flutter/issues/110014

**Comment by softlore** [comment]
sorry @maxim-saplin , I couldn't respond right away. Thanks for the response and explanation. The solution did not work for me. I am trying a alternate solution now and will update this thread if it works

**Comment by maxim-saplin** [comment]
@softlore , JIC you can switch to master channel, InkWell should be fixed there already. Though there's a risk of instability is other parts of SDK

**Comment by softlore** [comment]
thanks @maxim-saplin , switching to master fixed the issue
