### ISSUE TITLE
whenever I add an image inside a cell/row In data table it causes errors and screen becomes like this:

### ISSUE THREAD

**Issue by fisforfaheem** [maxim-saplin/data_table_2#131]
![image](https://user-images.githubusercontent.com/35878088/186673209-cd781a5d-1719-472f-aba7-8bba76d707fd.png)

**Comment by fisforfaheem** [comment]
code: 
![image](https://user-images.githubusercontent.com/35878088/186673545-26403c65-e307-4a44-8163-49e486f4902d.png)

**Comment by fisforfaheem** [comment]
and when i remove the image the error goes away
![image](https://user-images.githubusercontent.com/35878088/186673688-c5a6ef82-0fa4-4cb8-871d-e1765d7c0699.png)

**Comment by maxim-saplin** [comment]
Any error logs when that happens?

**Comment by fisforfaheem** [comment]
ok let me share a video

**Comment by maxim-saplin** [comment]
I'm talking of Debug output, what are the errors there?

**Comment by fisforfaheem** [comment]
here see it in action: https://clipchamp.com/watch/EmmqWzPxi1s

[GETX] REMOVING ROUTE /
2
1366
DataTable2 built: 2ms
[GETX] GOING TO ROUTE /BookingScreen
[GETX] REMOVING ROUTE /VerifiedUsersScreen
2
1366
DataTable2 built: 1ms
Another exception was thrown: NotFoundError: Failed to execute
'insertBefore' on 'Node': The node before which the new node is to be
inserted is not a child of this node.
Another exception was thrown: Unexpected null value.
Another exception was thrown: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/embedded_views.dart:696:16
46
Another exception was thrown: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/embedded_views.dart:616:16
[GETX] GOING TO ROUTE /VerifiedUsersScreen
[GETX] REMOVING ROUTE /BookingScreen
2
1366
DataTable2 built: 0ms
43
Another exception was thrown: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/embedded_views.dart:616:16

**Comment by maxim-saplin** [comment]
I don't see any errors related to data table, I suspect that you might have issue with ImageNetwork and it spoiling whatever UI there's.

**Comment by maxim-saplin** [comment]
Until you isolate a specific issue with the table of provide a self-contained minimal reproduction example that clearly showed how any of the package widgets misbehave - I won't be able to help you.

**Comment by fisforfaheem** [comment]
Suppose i want to add an ima,ge, avatar etc I an cell of datatabe how would
you do that?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
08/26/22,
12:17:39 AM

**Comment by maxim-saplin** [comment]
Just like you did

**Comment by maxim-saplin** [comment]
Should you have have any trouble with the package and can isolate and demonstrate the issue please create a new issue with all the details. This ticket is not actionable - you're firing my way general issue you didn't happen to do a decent troubleshooting and investigation.

**Comment by fisforfaheem** [comment]
Thank you!  I am a beginner developer and focus on front end, that's why i
am not on par with your standards of filing an issue.
