### ISSUE TITLE
Getting setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by santhoshrao519** [maxim-saplin/data_table_2#134]
I'm getting setState() or markNeedsBuild() called during build when i use PaginatedDataTable2. Please help

**Comment by maxim-saplin** [comment]
I don't have an idea what you are talking about...

**Comment by santhoshrao519** [comment]
When I'm using PaginatedDataTable2, the android studio returning "setState() or markNeedsBuild() called during build" error in the console

**Comment by maxim-saplin** [comment]
I don't get such errors

**Comment by dIvYaNshhh** [comment]
<img width="1178" alt="Screenshot 2023-03-04 at 6 46 32 PM" src="https://user-images.githubusercontent.com/6985574/222903949-af9949df-2ca8-4379-8ff6-5443053dbe9e.png">

This error i am getting with pagination when i am setting up the initalRowIndex

**Comment by maxim-saplin** [comment]
Minimal reproduction example?
