### ISSUE TITLE
<enhancement> bump to dart 2.18

### ISSUE THREAD

**Issue by fisforfaheem** [maxim-saplin/data_table_2#135]
it has many new features and more stable

**Comment by maxim-saplin** [comment]
I the package incompatible with 2.18 client code? The current pubspec.yaml constraint should allow any version between 2.17 and 3.0

**Comment by maxim-saplin** [comment]
How will the change of Dart to 2.18 in this package influence projects that regerence the package and target Dart versions below 2.18?

**Comment by fisforfaheem** [comment]
Language is more mature and many fixes in backend and while all other
packages use new version, this will help our app future proof
