### ISSUE TITLE
Enable Visible Vertical Scroll Bars

### ISSUE THREAD

**Issue by seachellemz** [maxim-saplin/data_table_2#140]
Allow the configuration of a visible vertical scrollbar.  While the data table supports both horizontal and vertical scrolling, it doesn't seem to provide a way to make the vertical scrollbar visible...even when the horizontal scrollbar is absent.

**Comment by maxim-saplin** [comment]
Try playing with themes, e.g.:

```
              child: Theme(
                  data: ThemeData(
                      scrollbarTheme: ScrollbarThemeData(
                          thumbVisibility: MaterialStateProperty.all(true), 
                          thumbColor:
                              MaterialStateProperty.all<Color>(Colors.black))),
                  child: DataTable2(
```

**Comment by seachellemz** [comment]
I've tried that.  I'm still not seeing a vertical scrollbar.  Here's the definition of my DataTable2:  

```
return Theme(
        data: ThemeData(
            scrollbarTheme: ScrollbarThemeData(
                thumbVisibility: MaterialStateProperty.all(true),
                thumbColor: MaterialStateProperty.all<Color>(Colors.orange))),
        child: DataTable2(
          columnSpacing: 0,
          horizontalMargin: 10.w,
          dataRowHeight: 30.h,
          scrollController: scrollController,
          sortAscending: _isAscending,
          sortColumnIndex: _sortColumnIndex,
          columns: getDataColumns(),
          rows: getDataRows(aisleMapList: aisleMapList),
        ));
```

Here is a screenshot of my DataTable as it is presented:  

<img width="433" alt="Screen Shot 2022-09-22 at 3 13 59 PM" src="https://user-images.githubusercontent.com/3332559/191832239-4fb9b8e2-769d-4931-b2c1-6c0c3abf0ff7.png">

**Comment by maxim-saplin** [comment]
Indeed the using the themes the scroll bar is visible on desktop platform (macOS) and is not shown in mobile platforms. I don't have answer to this, might be related to the specifics of Flutter SDK. Currently I don't have time to isolate and troubleshoot. 

If you do the research and share the results - that would be great

**Comment by Kingtous** [comment]
> Try playing with themes, e.g.:
> 
> ```
>               child: Theme(
>                   data: ThemeData(
>                       scrollbarTheme: ScrollbarThemeData(
>                           thumbVisibility: MaterialStateProperty.all(true), 
>                           thumbColor:
>                               MaterialStateProperty.all<Color>(Colors.black))),
>                   child: DataTable2(
> ```

same issue on the vertical scrollbar. using flutter 3.3.10 stable, the vertical scrollbar cannot be shown with this solution.

**Comment by maxim-saplin** [comment]
Pushed new 2.5.1 version to pub.dev, it fixes scrollbar themes on iOS and adds 2 properties to explicitly control scrollbar visibility
