### ISSUE TITLE
Failed assertion after rebuild

### ISSUE THREAD

**Issue by abdooobsl** [maxim-saplin/data_table_2#146]
hi , i am using data table2  to display data from api calling but after rebuild the widget to display data 
i get too many errors that doesn't do any effect on the performance but erorrs in console

like :
'package:flutter/src/rendering/table.dart': Failed assertion: line 632 pos 16: '_rows == 0': is not true.
'package:flutter/src/widgets/framework.dart': Failed assertion: line 6292 pos 12: 'child == _child': is not true.

before that it display in console flutter: DataTable2 built: 0ms
flutter is updated to last version and no issue in flutter doctor

**Comment by maxim-saplin** [comment]
Could you please share minimal repro example?

**Comment by abdooobsl** [comment]
`Container(
            child: state.reports.isNotEmpty
                ? Column(
                    children: [
                      Container(
                        margin: EdgeInsets.symmetric(horizontal: 10),
                        height: context.height * .67,
                        child: DataTable2(
                            columnSpacing: 12,
                            horizontalMargin: 12,
                            fixedCornerColor: lightTheme.secondaryHeaderColor,
                            fixedLeftColumns: 11,
                            border:
                                TableBorder.all(width: 2, color: lightTheme.secondaryHeaderColor, borderRadius: BorderRadius.circular(15)),
                            columns: [
                              DataColumn2(
                                  label: Text(
                                    "report_id".tr(),
                                    style: MediumTextStyle.display(),
                                  ),
                                  size: ColumnSize.S,
                                  // numeric: true,
                                  fixedWidth: 100),
                              DataColumn(
                                label: Text(
                                  "company_name".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "branch_name".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "window_department".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "service_name".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "window_employee".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn2(
                                  label: Text(
                                    "report_ticket".tr(),
                                    style: MediumTextStyle.display(),
                                  ),
                                  fixedWidth: 100),
                              DataColumn2(
                                  label: Text(
                                    "report_reserved_at".tr(),
                                    style: MediumTextStyle.display(),
                                  ),
                                  size: ColumnSize.S),
                              DataColumn(
                                label: Text(
                                  "report_current_status".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "report_last_action_time".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "actions".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                            ],
                            rows: List<DataRow>.generate(state.reports.length, (index) {
                              return DataRow(cells: [
                                DataCell(Text(
                                  state.reports[index].id.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].companyName.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].branchName.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].departmentName.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].serviceName.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].employeeName.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  getTicket(
                                    state.reports[index].reservationTurnNumber,
                                    state.reports[index].reservationPrefix,
                                  ).toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].reservedAt.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].currentStatus.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].actions.last.time.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(
                                  Center(
                                    child: Card(
                                      elevation: 10,
                                      color: lightTheme.secondaryHeaderColor,
                                      child: Container(
                                        padding: EdgeInsets.symmetric(horizontal: 10),
                                        child: InkWell(
                                          onTap: () {
                                            reportBloc.currentReport=state.reports[index];
                                            reportBloc.add(ReportSelected());
                                            showDialog(
                                                context: context,
                                                barrierDismissible: false,
                                                builder: (context) {
                                                  Widget continueButton = TextButton(
                                                    child: Text(
                                                      'close'.tr(),
                                                      style: NormalMainColorTextStyle.display(),
                                                    ),
                                                    onPressed: () {
                                                      Navigator.pop(context);
                                                    },
                                                  );
                                                  return AlertDialog(
                                                    actions: [
                                                      continueButton,
                                                    ],
                                                    content: ReportViewComponent(currentReport:state.reports[index] ,),
                                                  );
                                                });
                                          },
                                          child: Text(
                                            "report_view".tr(),
                                            style: MediumTextStyle.display(),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ]);
                            })),
                      ),
                    ],
                  )
                : Center(
                    child: Text(
                      "report_no_data".tr(),
                      style: LargeMainColorTextStyle.display(),
                    ),
                  ))`

**Comment by abdooobsl** [comment]
`Container(
            child: state.reports.isNotEmpty
                ? Column(
                    children: [
                      Container(
                        margin: EdgeInsets.symmetric(horizontal: 10),
                        height: context.height * .67,
                        child: DataTable2(
                            columnSpacing: 12,
                            horizontalMargin: 12,
                            fixedCornerColor: lightTheme.secondaryHeaderColor,
                            fixedLeftColumns: 11,
                            border:
                                TableBorder.all(width: 2, color: lightTheme.secondaryHeaderColor, borderRadius: BorderRadius.circular(15)),
                            columns: [
                              DataColumn2(
                                  label: Text(
                                    "report_id".tr(),
                                    style: MediumTextStyle.display(),
                                  ),
                                  size: ColumnSize.S,
                                  // numeric: true,
                                  fixedWidth: 100),
                              DataColumn(
                                label: Text(
                                  "company_name".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "branch_name".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "window_department".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "service_name".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "window_employee".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn2(
                                  label: Text(
                                    "report_ticket".tr(),
                                    style: MediumTextStyle.display(),
                                  ),
                                  fixedWidth: 100),
                              DataColumn2(
                                  label: Text(
                                    "report_reserved_at".tr(),
                                    style: MediumTextStyle.display(),
                                  ),
                                  size: ColumnSize.S),
                              DataColumn(
                                label: Text(
                                  "report_current_status".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "report_last_action_time".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                              DataColumn(
                                label: Text(
                                  "actions".tr(),
                                  style: MediumTextStyle.display(),
                                ),
                              ),
                            ],
                            rows: List<DataRow>.generate(state.reports.length, (index) {
                              return DataRow(cells: [
                                DataCell(Text(
                                  state.reports[index].id.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].companyName.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].branchName.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].departmentName.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].serviceName.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].employeeName.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  getTicket(
                                    state.reports[index].reservationTurnNumber,
                                    state.reports[index].reservationPrefix,
                                  ).toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].reservedAt.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].currentStatus.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(Text(
                                  state.reports[index].actions.last.time.toString(),
                                  style: MediumMainColorTextStyle.display(),
                                )),
                                DataCell(
                                  Center(
                                    child: Card(
                                      elevation: 10,
                                      color: lightTheme.secondaryHeaderColor,
                                      child: Container(
                                        padding: EdgeInsets.symmetric(horizontal: 10),
                                        child: InkWell(
                                          onTap: () {
                                            reportBloc.currentReport=state.reports[index];
                                            reportBloc.add(ReportSelected());
                                            showDialog(
                                                context: context,
                                                barrierDismissible: false,
                                                builder: (context) {
                                                  Widget continueButton = TextButton(
                                                    child: Text(
                                                      'close'.tr(),
                                                      style: NormalMainColorTextStyle.display(),
                                                    ),
                                                    onPressed: () {
                                                      Navigator.pop(context);
                                                    },
                                                  );
                                                  return AlertDialog(
                                                    actions: [
                                                      continueButton,
                                                    ],
                                                    content: ReportViewComponent(currentReport:state.reports[index] ,),
                                                  );
                                                });
                                          },
                                          child: Text(
                                            "report_view".tr(),
                                            style: MediumTextStyle.display(),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ]);
                            })),
                      ),
                    ],
                  )
                : Center(
                    child: Text(
                      "report_no_data".tr(),
                      style: LargeMainColorTextStyle.display(),
                    

> ),

                  

> ))`

**Comment by abdooobsl** [comment]
all api now on local host but i could provide team viewer or anydesk

**Comment by maxim-saplin** [comment]
If you want me to help you please provide a runnable reproduction case which can be extracted and started right away. Based on your inputs I can neither reproduce the issue nor see any bug related to the package itself.
