### ISSUE TITLE
Try correcting the name to the name of an existing method, or defining a method named 'MaterialStatePropertyAll'

### ISSUE THREAD

**Issue by madmouse17** [maxim-saplin/data_table_2#147]
- 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/D:/flutter/.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart').
package:data_table_2/src/data_table_2.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'MaterialStatePropertyAll'.
                            ? MaterialStatePropertyAll(fixedColumnsColor
please how to fix it?

**Comment by maxim-saplin** [comment]
Try running `flutter upgrade`, it seems you are using older version of framework with missing dependancy
