### ISSUE TITLE
 the method materialstatePropertyall is not define for the class datatable2 

### ISSUE THREAD

**Issue by shyamfuturellp2022** [maxim-saplin/data_table_2#148]
(https://github.com/maxim-saplin/data_table_2/files/9926120/datatable2.txt)

- This is the code for datatable2 , run it in xcode(ios)  this  "the method materialstatePropertyall is not define for the class datatable2" error occur.

**Comment by erofcon** [comment]
I confirm. I have the same

**Comment by erofcon** [comment]
in version 2.3.7 works correctly

**Comment by blayziken** [comment]
Experiencing the same issue right now

**Comment by shyamfuturellp2022** [comment]
> in version 2.3.7 works correctly

I have used the same version.
I have facing this issue for iOS only when I am trying to run flutter app in iOS.
It is working fine in Android.
 ../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart:547:31: Error: The method 'MaterialStatePropertyAll' isn't defined for the class 'DataTable2'.
     - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'MaterialStatePropertyAll'.
                                ? MaterialStatePropertyAll(fixedColumnsColor)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart:553:31: Error: The method 'MaterialStatePropertyAll' isn't defined for the class 'DataTable2'.
     - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'MaterialStatePropertyAll'.
                                ? MaterialStatePropertyAll(fixedColumnsColor)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart:567:27: Error: The method 'MaterialStatePropertyAll' isn't defined for the class 'DataTable2'.
     - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'MaterialStatePropertyAll'.
                            ? MaterialStatePropertyAll(fixedColumnsColor)
                              ^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart:616:31: Error: The method 'MaterialStatePropertyAll' isn't defined for the class 'DataTable2'.
     - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'MaterialStatePropertyAll'.
                                ? MaterialStatePropertyAll(fixedCornerColor)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart:625:31: Error: The method 'MaterialStatePropertyAll' isn't defined for the class 'DataTable2'.
     - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'MaterialStatePropertyAll'.
                                ? MaterialStatePropertyAll(fixedCornerColor)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart:631:31: Error: The method 'MaterialStatePropertyAll' isn't defined for the class 'DataTable2'.
     - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.8/lib/src/data_table_2.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'MaterialStatePropertyAll'.
                                ? MaterialStatePropertyAll(fixedCornerColor)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by maxim-saplin** [comment]
You have to run `flutter upgrade` in order to get the most recent version of SDK.

**Comment by shyamfuturellp2022** [comment]
> You have to run `flutter upgrade` in order to get the most recent version of SDK.

Thanks for your help. Now it is woking fine.
