### ISSUE TITLE
wrong initial direction of ascending arrow

### ISSUE THREAD

**Issue by AMuellerAtAHS** [maxim-saplin/data_table_2#15]
Hello,

I got some strange behaviour of the ascending arrow. 

When I show the datatable, the order of the rows is correct but the arrow is showing to the opposite direction. 

![grafik](https://user-images.githubusercontent.com/77151644/122549164-78e2be00-d032-11eb-8756-8d8c942f80cf.png)

When I switch the order to another column and back to the initial column everything works fine.

![grafik](https://user-images.githubusercontent.com/77151644/122549299-9e6fc780-d032-11eb-8ae1-385cdf0036e6.png)

**Comment by maxim-saplin** [comment]
I assume you set default sort direction when the table is displayed for the first time (by default there's no sorting by any column)? Can you show you source code the the DataTable2?

**Comment by AMuellerAtAHS** [comment]
Yes you are right. I set default direction to descending and default column to zero. Like you can see in the pictures, the sorting functionality works fine. 

Here are some parts of my code.  If you need more information please let me know.
```
// default values
 int sortColumnIndex = 0;
 bool sortAscending = false;
 String sortPropertyName = 'dateTime';
```
 
```
// Datatable2, Columns and Rows are separated
Widget _buildDataTable(List<LogEntry> entries) {
    return Expanded(
      flex: 1,
      child: Padding(
        padding: EdgeInsets.symmetric(vertical: 16.0),
        child: DataTable2(
            columnSpacing: 0,
            horizontalMargin: 12,
            bottomMargin: 10,
            minWidth: 600,
            scrollController: _scrollController,
            sortAscending: sortAscending, // initial false
            sortColumnIndex: sortColumnIndex, // initial 0
            columns: _buildDataColumns(),
            rows: _buildDataRows(entries)),
      ),
    );
  }
```
For the sorting functionality I have three parts.
```
// create columns with on sort signal handler, which is called when you click on the header
List<DataColumn2> _buildDataColumns() {
    List<DataColumn2> columns = <DataColumn2>[
      DataColumn2(
        onSort: (int columnIndex, ascending) =>
            onSort(columnIndex, ascending, 'dateTime'),

// on sort signal handler, set  values for sorting
void onSort(int columnIndex, bool ascending, String propertyName) {
    setState(() {
      sortColumnIndex = columnIndex;
      sortAscending = ascending;
      sortPropertyName = propertyName;
    });
    sortLogEntries();
  }

// sort the entries, if not ascending, reverse entries after wards
  void sortLogEntries() {
    setState(() {
      _logEntries.sort(
          (a, b) => a.get(sortPropertyName).compareTo(b.get(sortPropertyName)));
      if (!sortAscending) _logEntries = _logEntries.reversed.toList();
    });
    filterLogEntries();
  }
````

**Comment by AMuellerAtAHS** [comment]
I also looked at the code of data_table_2.dart. At row 122 I found an intializer of sortAscending. Could this be the reason?

```
class DataTable2 extends DataTable {
  DataTable2({
    Key? key,
    required List<DataColumn> columns,
    int? sortColumnIndex,
    bool sortAscending = true,
```

**Comment by maxim-saplin** [comment]
Looked at the sample you provided. The problem is not related to the DataTable2 showing wrong direction, it shows whatever direction it is told to show. The problem is due to data source being out of sync and not sorted according to values of sortAscending, sortColumnIndex properties. DataTable2 being a statless widget relies on state management handled above it.

In your case I suggest to have the data source sorted on state init and from that point all will be good.

**Comment by AMuellerAtAHS** [comment]
OK thank you. 
So you mean that the initial values sortAscending and sortColumnIndex don't fit to the initial sorting of the data. Do you? 
But I use the same value (`sortAscending`) for the direction of the arrow and for sorting the datasource.  I just load and sort the datasource after initialising the app, cause I have to wait for http request.

**Comment by maxim-saplin** [comment]
> So you mean that the initial values sortAscending and sortColumnIndex don't fit to the initial sorting of the data. Do you?
That's right.

Are you sure that the datasource provided to the widget has the same sorting as the value provided to the same widget via sortAscending, sortColumnIndex? Cause widget doesn't have any instrinsic sorting capabilties.

**Comment by AMuellerAtAHS** [comment]
Thank you.

I'm not really sure about that, but I add some debugging statements inside the _buildDataTable 

```
  Widget _buildDataTable(List<LogEntry> entries) {
    print(
        '_buildDataTable sortAscending = $sortAscending | sortColumnIndex = $sortColumnIndex | sortPropertyName = $sortPropertyName');
    return Expanded(
      flex: 1,
      child: Padding(
        padding: EdgeInsets.symmetric(vertical: 16.0),
        child: DataTable2(
            columnSpacing: 0,
            horizontalMargin: 12,
            bottomMargin: 10,
            minWidth: 600,
            scrollController: _scrollController,
            sortAscending: sortAscending, // initial false
            sortColumnIndex: sortColumnIndex, // initial 0
            columns: _buildDataColumns(),
            rows: _buildDataRows(entries)),
      ),
    );
  }
```

and the sortLogEntries function.

```
void sortLogEntries() {
    print(
        'sortLogEntries sortAscending = $sortAscending | sortColumnIndex = $sortColumnIndex | sortPropertyName = $sortPropertyName');
    setState(() {
      _logEntries.sort(
          (a, b) => a.get(sortPropertyName).compareTo(b.get(sortPropertyName)));
      if (!sortAscending) _logEntries = _logEntries.reversed.toList();
    });
    filterLogEntries();
  }
```

Then I tested the app (Webapp hosted on apache2 webserver) and loaded the page with the data_table_2.
First it shows me the `_buildDataTable print` output. When the entries were updated it throws the `print` output of `sortLogEntries` and the `_buildDataTable print` output again. I attached a screenshot of the console output.

![debug_ascending_data_table_2](https://user-images.githubusercontent.com/77151644/123040901-cd9c8500-d3f4-11eb-89d0-cd2b98d5d999.PNG)

Do you know if the display of the arrow works, when the data table has no data? Also is it just triggering from up to down and vice versa?

**Comment by maxim-saplin** [comment]
There's an updated example at https://github.com/maxim-saplin/data_table_2/blob/main/example/lib/data_table2.dart

You can check how default sorting is implemented there, see the commented part:

```
      // Default sorting sample. Set __sortColumnIndex to 0 and uncoment the lines below
      // if (_sortColumnIndex == 0) {
      //   _sort<String>((d) => d.name, _sortColumnIndex!, _sortAscending);
      // }
```

> Do you know if the display of the arrow works, when the data table has no data? Also is it just triggering from up to down and vice versa?

Widget displays whatever sorting it is told to regardless of the datasource:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/7947027/123055205-4e1baf80-d40e-11eb-98d9-d3f5e715aab7.png">

**Comment by AMuellerAtAHS** [comment]
Thanks a lot for your help. 

Finally I fixed my code to initialize data_table with sort ascending true and switcht to false, when the data is loaded. 

```
int _sortColumnIndex = 0;
bool _sortAscending = true;
```
```
void updateLogs(Timer timer) async {
    var futureEntries = await fetchEntry();
    _logEntries = futureEntries;
    if (!_initialized) {
      setState(() {
        _sortAscending = false;
        _sortColumnIndex = 0;
        _initialized = true;
      });
    }
    sortLogEntries();
  }
```
