### ISSUE TITLE
disable row tap

### ISSUE THREAD

**Issue by YouSour** [maxim-saplin/data_table_2#150]
hi, is it possible to disable row tap ? i want user tap directly on checkbox only, thank in advance

**Comment by maxim-saplin** [comment]
Don't get you. Tap events are opt in, you can't disable smth you don't use.

**Comment by YouSour** [comment]
@maxim-saplin thank you for reply, what i mean is i don't want user tap on row  call func check the checkbox , i want to user check the check box when user tap on checkbox directly , this package if i don't use onSelectChanged() on row it doesn't show the checkbox and it come with row tap , i want to know is it possible  disable it or not or i need to implement by myself.

**Comment by maxim-saplin** [comment]
You can try defining both event handlers, on selected and on row tap,leaving roe tap handler empty. In this case you should get the check biz click issuing on select event. There was a change in 2.3.7 version that addresses your case:

2.3.7

    Row tap events now do not bubble onSelectChanged() event handler, yet it still fires if there's a checkbox column and a checkbox is clicked (PR #133)
