### ISSUE TITLE
how to fix left column(sticky left column) using DataTable2

### ISSUE THREAD

**Issue by shyamfuturellp2022** [maxim-saplin/data_table_2#151]
how to fix left column(sticky left column) using DataTable2

**Comment by maxim-saplin** [comment]
Set `DataTable2.fixedLeftColumns` to the number of columns you want fixed

**Comment by shyamfuturellp2022** [comment]
DataTable2 _createPlantDataTablewithoutAmended() {
    return DataTable2(
        columnSpacing: 15,
        horizontalMargin: 30,
        minWidth: 1200,
        border: TableBorder(
            top: const BorderSide(color: Colors.black),
            bottom: BorderSide(color: Colors.grey[300]!),
            left: BorderSide(color: Colors.grey[300]!),
            right: BorderSide(color: Colors.grey[300]!),
            verticalInside: BorderSide(color: Colors.grey[300]!),
            horizontalInside:
            const BorderSide(color: Colors.grey, width: 1)),
        dividerThickness: 1, // this one will be ignored if [border] is set above
        columns: createPlantDataColumnswithoutAmended(), rows: createPlantDataRowswithoutAmended());
  }
please  help where we put  this code or give some example so that we continue it

**Comment by maxim-saplin** [comment]
Are you kidding? You're asking me how to set widget's field. Please don't spam the repo with questions not related to the widget and do basic learning or Flutter and Dart

**Comment by yogithesymbian** [comment]
ah i got it
```
return DataTable2(
      fixedLeftColumns: 2, // here is properties
```
can we sticky only for specify columns for example in middle of item column, i have 20 item

| item 1  | item 2 | item 3  | item 4 |
| ------------- | ------------- |  ------------- | ------------- |
| Content Cell  | Content Cell  | Content Cell  | Content Cell  |
| Content Cell  | Content Cell  | Content Cell  | Content Cell  |

then we need sticky only on `item 3`
