### ISSUE TITLE
Anyway to set width on specific column?

### ISSUE THREAD

**Issue by GiddyNaya** [maxim-saplin/data_table_2#154]
I have been wrapping my head on how to set a specific width on Serial Number column as it seems the width of all columns are equally distributed. I've tried the below code on the cell but no luck:
```
DataCell(ConstrainedBox(
              constraints: BoxConstraints(maxWidth: 50), //SET max width
              child: Text("#${index + 1}")))
```

Also tried:

```
DataCell(SizedBox(
              width: 50, //SET max width
              child: Text("#${index + 1}")))
```

![WhatsApp Image 2022-11-26 at 12 48 48 PM](https://user-images.githubusercontent.com/16220887/204087659-7830692c-b6af-4aa0-9f08-715e7d54b925.jpeg)

**Comment by maxim-saplin** [comment]
Hi, SziedBox won't help.

Fixed width can be set at column definition, check DataCoulm2.fixedWidth
