### ISSUE TITLE
PaginatedDataTable2 shows wrong number of total rows on last page

### ISSUE THREAD

**Issue by DeddyH** [maxim-saplin/data_table_2#156]
Let' s say, my datasource contains 15 records and 10 of them are displayed once in a while. Then the footer displays "11 - 20 of 15" on the last page, which is quite confusing. I suggest the following change in footerWidgets.addAll:

```
Text(

        localizations.pageRowsInfoTitle( 

          _firstRowIndex + 1,

          math.min(_rowCount, _firstRowIndex + _effectiveRowsPerPage), // take the lower number  

          _rowCount,  

          _rowCountApproximate,  

        ),  

      ),
```

**Comment by maxim-saplin** [comment]
That's how the SDKs PaginatedDataTable works, shows empty rows to fill the page. For consistency that behavior will be preserved.

There was also a PR with one of the parts containing a toggle for that behavior, should it eventually be completed the capability to override that behavior will be added

**Comment by DeddyH** [comment]
My issue was not about showing empty rows, but the displayed number within the footer.

**Comment by maxim-saplin** [comment]
Those are related, you get number in the future corresponding to the number of rows displayed, empty rows counted in

**Comment by DeddyH** [comment]
OK, but that is kind of weird in my opinion.

**Comment by maxim-saplin** [comment]
It's Flutters or Material design default way of displaying paginated tables...

**Comment by maxim-saplin** [comment]
`PaginatedDataTable2.renderEmptyRowsInTheEnd` property has recently been added, try setting it to false, should fix your issue

**Comment by DeddyH** [comment]
Thank you very much. Meanwhile I reported this issue to the flutter-team itself: https://github.com/flutter/flutter/issues/116569
