### ISSUE TITLE
PaginatedDataTable2 auto rowsPerPage based on widget height 

### ISSUE THREAD

**Issue by Josua2012** [maxim-saplin/data_table_2#16]
Hello,
Does your PaginatedDataTable2 widget allow the number of rowsPerPage to be automatic based on the height of the widget (fit: FlexFit.tight) on the page?
If it doesn't allow it, this functionality would be very interesting since when making the web page or desktop app bigger (height), PaginateDataTable2 would automatically show more or fewer lines without the need for the user to change them manually. 
Thank you very much for adding all these new features to the PaginatedTableView, they were very necessary.  💯 🥇 
Regards,
Jose

**Comment by maxim-saplin** [comment]
Hi, there's no such feature at the moment, need to think of the implementation..

**Comment by Josua2012** [comment]
Many thanks Maxim.

**Comment by KristianBalaj** [comment]
+1

Yeah this is an actual issue on web and desktop platforms where window can be resized. When the window is resized to small size, some rows get invisible and a user cannot even scroll to them. Needing to scale back to the larger window size.

**Comment by maxim-saplin** [comment]
Just published 2.1.0 to pub.dev. Now there's autoRowsToHeight property on PaginatedDataTable2, an example is also provided/updated (https://maxim-saplin.github.io/data_table_2/)

**Comment by Josua2012** [comment]
Marvelous. I love.
However, there is a serious problem that needs to be corrected, since in my case it causes me to not be able to use the new autoRowsToHeight property.
Changing the number of rows does not raise the onRowsPerPageChanged event.
I use it to fetch records from a nodejs server.
It would also be very interesting if the execution of onRowsPerPageChanged could be debounced, that is, that the onRowsPerPageChanged event does not execute for each change of rowsPerPage in the case of several property changes very quickly.
Check out the following video: https://recordit.co/JT0UWm2y6x
If you have any questions about what I have told you, tell me. 
Thank you very much for your hard work. 
Regards,
Jose
