### ISSUE TITLE
Fix right column

### ISSUE THREAD

**Issue by logeshwaran0608** [maxim-saplin/data_table_2#160]
Hi, now DataTable2 has left side sticky in the table, please create or help me to fix right side sticky for the tables actually I need that right side sticky.  please help me to fix!!!

**Comment by maxim-saplin** [comment]
That's a solid chunk of work, adding that kind of feature to the packages, no plans to work on it.

You might try creating your own UI without this package by using SDK's DataTable and putting 2 widgets in 2 columns with scrollable and working on scroll syncing.

**Comment by logeshwaran0608** [comment]
Okie, thanks...

**Comment by yogithesymbian** [comment]
hope fix

**Comment by yogithesymbian** [comment]
<img width="463" alt="appreciate" src="https://github.com/maxim-saplin/data_table_2/assets/28316296/71bfd63d-841b-4743-b642-ff7219a4ba2c">
expected :D you are awesome , please make it bro from fixedRightColumn 💯
