### ISSUE TITLE
_AssertionError  &&  Could not load source 'dart:core-patch/errors_patch.dart': <source not available>.

### ISSUE THREAD

**Issue by iremceliksena** [maxim-saplin/data_table_2#161]
Hi @maxim-saplin  ,
I have a project where I use PaginatedDataTable and I converted PaginatedDataTable to PaginatedDataTable2. And I wanted to show [5,10, all records] in this PaginatedDataTable, like this: 
![githh1](https://user-images.githubusercontent.com/121493659/209666985-ae4fc3fb-65ff-49cb-850c-21f05d59551c.JPG)

And i can do this but when i switched to PaginatedDataTable2, I couldn't do anything on my records while all records option was selected. And I am getting the following errors:
![githh2](https://user-images.githubusercontent.com/121493659/209667112-9605317d-4ae1-4fe3-873c-8514aa1adbc8.JPG)
![hatasource](https://user-images.githubusercontent.com/121493659/209667221-2545098a-89b6-44bd-93a6-28bb0f379478.JPG)

How can i fix this problem, everything in the project is the same except PaginatedDataTable.

**Comment by maxim-saplin** [comment]
Hi, unfortunately the description provided doesn't give any detail. Please the exact error (not some generic SDK file with irrelevant debug message) as well as code snippets that cause the error

**Comment by iremceliksena** [comment]
In my project, i am fetching data from api and displayin this data in PaginatedDataTable2 and i have buttons on the DataCells such as delete, update, add new record. In the case that i list all my records in PaginatedDataTale2 using the code below, when i try to perform any action using these buttons, i get the errors that i have put the images below. Same code directory was working fine with PaginatedDataTable.

### PaginatedDataTable2 code block:
`PaginatedDataTable2(
                    renderEmptyRowsInTheEnd: true,
                    horizontalMargin: AppDesktopTheme.pTableViewHorizantalSpace,
                    dataRowHeight: 55,
                    columnSpacing: 13,
                    sortAscending: sort,
                    sortColumnIndex: _sortColumnIndex,
                    availableRowsPerPage: PgDataTable.rowCount(
                        length: listController.dataList.length),
                    columns: [
                      DataColumn2(
                          fixedWidth: 50,
                          label: Text(
                            "Sıra",
                            style: Get.textTheme.headline6,
                          )),
                      DataColumn(
                          label: Container(
                              alignment: Alignment.centerLeft,
                              child: Text("İşletme Adı",
                                  style: Get.textTheme.headline6)),
                          onSort: (columnIndex, ascending) {
                            setState(() {
                              sort = !sort;
                              _sortColumnIndex = columnIndex;
                            });
                            onSortColum(columnIndex, ascending);
                          }),
                      DataColumn2(
                          fixedWidth: 120,
                          label: Text(
                            'Toplam\nÖgrenci\nSayısı',
                            style: Get.textTheme.headline6,
                            textAlign: TextAlign.center,
                          ),
                          onSort: (columnIndex, ascending) {
                            setState(() {
                              sort = !sort;
                              _sortColumnIndex = columnIndex;
                            });
                            onSortColum(columnIndex, ascending);
                          }),
                      DataColumn2(
                        fixedWidth: 120,
                        label: Text(
                          'Ögrenci\nSözleşmeleri',
                          style: Get.textTheme.headline6,
                          textAlign: TextAlign.center,
                        ),
                      ),
                      DataColumn2(
                        fixedWidth: 120,
                        label: Text(
                          'Ögrenci\nAtamaları',
                          style: Get.textTheme.headline6,
                          textAlign: TextAlign.center,
                        ),
                      ),
                      DataColumn2(
                        fixedWidth: 120,
                        label: Text(
                          'İhtiyaç\nTalebi',
                          style: Get.textTheme.headline6,
                          textAlign: TextAlign.center,
                        ),
                      ),
                      DataColumn2(
                        fixedWidth: 100,
                        label: Text(
                          "Güncelle",
                          style: Get.textTheme.headline6,
                          textAlign: TextAlign.center,
                        ),
                      ),
                      DataColumn2(
                        fixedWidth: 50,
                        label: Center(
                            child: Text("Sil", style: Get.textTheme.headline6)),
                      ),
                    ],
                    source: DTS(),
                    rowsPerPage: _rowPerPageCustom != 0
                        ? _rowPerPage
                        : Get.height < 900
                            ? _rowPerPage = 5
                            : _rowPerPage = 10,
                    onRowsPerPageChanged: (r) {
                      setState(() {
                        _rowPerPageCustom = r!;
                        _rowPerPage = r;
                      });
                    },
                  ),`

### PgDataTable class
`class PgDataTable {
  static List<int> rowCount({required int length}) {
    List<int> rowsCount = [];

    if (length <= 10) {
      rowsCount.addAll([5, 10]);
      print(rowsCount);

      return rowsCount;
    }

    rowsCount.addAll([5, 10, length]);
    print(rowsCount);

    return rowsCount;
  }
}
`

### Error Images :
![hata5](https://user-images.githubusercontent.com/121493659/209678358-58bf10a2-7213-4c26-ab1c-8cfb2938de06.JPG)
-------------------------------------------------------
![hata6](https://user-images.githubusercontent.com/121493659/209678397-227508f1-adff-4b9b-a6ef-c2a94a7d0e12.JPG)
-------------------------------------------------------
![hata7](https://user-images.githubusercontent.com/121493659/209678485-c1279002-dc3c-4f7f-b139-b8a7b92ea3d3.JPG)
--------------------------------------------------------
![hata8](https://user-images.githubusercontent.com/121493659/209678507-f77becc8-9c80-4cb6-ad43-21ac15919c19.JPG)
---------------------------------------------------------

When i press any button it goes to 'errors.patch.dart' (Could not load source 'dart:core-patch/errors_patch.dart': <source not available>.)error page and whole app screen freezes.

**Comment by maxim-saplin** [comment]
The error log says that values provided to DropdownButton are incorrect, probably value 92 is met not once. I'd suggest checking what is passed to `availableRowsPerPage` field of the table and check if something wrong with values used to set up pager.

**Comment by iremceliksena** [comment]
I keep the length of my dataset in the variable PgDataTable.rowCount(length: listController.dataList.length) and return a dynamic list as [5,10,length] for the avaliableRowsperPage. I think it gives an error because the length changes in adding and removing records. How can i send a dynamic list into avaliableRowsperPage? Or is it possible in any way with PaginatedDataTable2 ?

**Comment by maxim-saplin** [comment]
I am not sure I understand what you are trying to tell..

**Comment by iremceliksena** [comment]
Hi,
I solved my problem. The widget was taking the _effectiveRowsPerPage as value instead of the widget.rowsPerPage  in Widget _getFooter(). I fixed this situation by making changes in the package. Thanks for your help. I am adding solution images for people who may experience the same problems after me.

### _getFooter() before changes:
![pdt2](https://user-images.githubusercontent.com/121493659/209797637-67383e06-853b-479b-99cb-2a2f2d2944c4.JPG)

### _getFooter() after changes:

![pdt2 1](https://user-images.githubusercontent.com/121493659/209797653-5a0ff267-1a69-44d4-ad83-3144dde5958f.JPG)
