### ISSUE TITLE
TableRowInkWell painting outside the boundaries of widget

### ISSUE THREAD

**Issue by AKovynev** [maxim-saplin/data_table_2#165]
Hi. Since there is no way to set the width of the column, I picked up the minimum width of the entire table. But I don't need to display all of table. However, traces remain of it, how to get rid of it?
```
Widget build(BuildContext context) {
    return Container(
      height: 500,
       width: 620,
      child: DataTable2(
        border: TableBorder.all(width: 1.0, color: Colors.brown),
        minWidth: 2500,
```
![image](https://user-images.githubusercontent.com/118714968/216063375-e6e327ec-f37b-4564-a385-ca0008d27ebc.png)

**Comment by maxim-saplin** [comment]
Don't get it

**Comment by AKovynev** [comment]
> Don't get it

I put a table with a minimum width of 2500 in a Container with a width of 620. Part of the table is hidden and I can view it using scroll. But when you hover over a row, a trace of the line appears outside the container.  I'm a total newbie, windows desktop app.

**Comment by maxim-saplin** [comment]
I see... When hovering over a row RowInkWell is used to highlight the row and there's a sort of bug (or feature) in Flutter SDK when that row is for some reasons drawn outside of the boundaries of a row. Option one is change hovering style and color to transparent. Option 2 is put some coloured widget to the right of the table to have it covering whatever region RowInkWell might want to draw at

**Comment by AKovynev** [comment]
> I see... When hovering over a row RowInkWell is used to highlight the row and there's a sort of bug (or feature) in Flutter SDK when that row is for some reasons drawn outside of the boundaries of a row. Option one is change hovering style and color to transparent. Option 2 is put some coloured widget to the right of the table to have it covering whatever region RowInkWell might want to draw at

Thanks, Maxim. I will try.

**Comment by maxim-saplin** [comment]
Keeping that issue as a bug.

Should the widget be scrolled horizontally and row hovered it is possible the hovered row will display hover color outside the widget. That should be investigated and fixed:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/7947027/216256723-cbf976f3-4bf5-4ccd-a707-d2a335dd6d4b.png">

**Comment by savadodesigns** [comment]
I would love to see a fix as well. Subscribing. +1

**Comment by maxim-saplin** [comment]
Wrapping widgets in Material should fix hover overflow:

```
Material(
          child: DataTable2(
```

I'll see how to get it properly fixed in the widgets without breaking anything.

**Comment by EBBozkurt** [comment]
> Wrapping widgets in `Material` should fix hover overflow:
> 
> ```
> Material(
>           child: DataTable2(
> ```
> 
> I'll see how to get it properly fixed in the widgets without breaking anything.

I had a problem with hovering a data row and hover didn't show when I hover to data row. I also had same issue which is hover overflow.

This answer fixed both.

**Comment by maxim-saplin** [comment]
The fix has been published to pub.dev. Enjoy)
