### ISSUE TITLE
Stack in every row

### ISSUE THREAD

**Issue by martinpelli** [maxim-saplin/data_table_2#166]
Hi, I am opening an issue but I don't really know if this is an issue or a feature or a possible thing to do.

I need to put a text widget in the middle of two cells (as cells merging is not supported, I am putting no border  between the cells that I want so is like is one cell instead of two). I had the idea of using a stack to put the Text widget in the middle of the two cell that looks like one. 

But the problem is that the stack works only with it's children, so, there is no way to return Stacks instead of DataRow in the rows property of DataTable2? I mean, rows of Stacks?? Is there any way to achieve this?? (putting the six between two cells)

![image](https://user-images.githubusercontent.com/63437171/216177675-1b112334-a90a-4481-89a5-9c52878df8e8.png)

**Comment by martinpelli** [comment]
Okay, I think you can close this, It was just in case there was something that I didn't realize.  Thanks for your response maybe I will check custom painter.

**Comment by martinpelli** [comment]
@maxim-saplin 
Also I take this opportunity to ask, in case there is need to open a new issue.

The thing is that when putting a container filled with a color in DataCells, even putting dividerThickness: 0 there still are some lines less than 1 height that can be seen between rows.
![image](https://user-images.githubusercontent.com/63437171/216690612-324fcd21-9808-43ee-ba9c-2346c43bcbb9.png)

**Comment by maxim-saplin** [comment]
I beleive those are the artefacts related to pixel density and some cells not taking 100 of physical pixels. Might need further investigation

**Comment by maxim-saplin** [comment]
Would be great to have a separate issue with minimal reproduction code
