### ISSUE TITLE
PageStorageBucket Nullsafety Bug when building with 2.3.11

### ISSUE THREAD

**Issue by militaumbro** [maxim-saplin/data_table_2#167]
I tried building my flutter project with the new 2.3.11 and when building for release and debug it conflicted with PageStorageBucket and the building process ended in failure. 
The problem doesnt occur with 2.3.7

../../../../flutter/.pub-cache/hosted/pub.dartlang.org/data_table_2-2.3.11/lib/src/paginated_data_table_2.dart
(494,46): error G7AD6136F: Method 'readState' cannot be called on 'PageStorageBucket?' because it is potentially 
null. [FILEPATH\src\build\windows\flutter\flutter_assemble.vcxproj]
../…/src/paginated_data_table_2.dart:1
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: o build personalizado para [FILEPATH\src\build\windows\CMakeFiles\fbba30c2a1b7e4873ebfd96c383cd084\flutter_windows.dll.rule;[FILEPATH\src\build\windows\CMakeFiles\f105d650208ce1124a57984cbe3eedd2\flutter_assemble.rule' foi encerrado com o c�digo 1. [FILEPATH\src\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.

**Comment by maxim-saplin** [comment]
The widget has been updated with Flutter 3.7 release, apparently there're differences that break widget with previous SDK version. I'd suggest upgrading flutter or reveret data table to -1 version

**Comment by maxim-saplin** [comment]
JIC, I've pushed 2.3.12 yesterday with Flutter version constraint >= 3.7.0
