### ISSUE TITLE
Hide loader for columns in row in paginated data table 2

### ISSUE THREAD

**Issue by WasimMemon** [maxim-saplin/data_table_2#173]
How to hide or remove loader from each column in row in paginated data table 2 ?
When new row data getting fetched from database, this kind of loader gets displayed. 

Flutter SDK : 3.7.0
data_table_2: ^2.3.12

<img width="863" alt="Screenshot 2023-02-17 at 10 53 58 PM" src="https://user-images.githubusercontent.com/6543095/219876048-064aadff-61e5-42e7-82f5-022e96c6152b.png">

**Comment by maxim-saplin** [comment]
I believe you have null rows which get displayed as progress indicators, don't return null rows, that should not display that kind of animations.

JIC, here's the piece of code responsible for the behaviour:

![image](https://user-images.githubusercontent.com/7947027/219883112-4e4bbe01-f9a4-4dce-90c9-28f2fea4f486.png)

**Comment by WasimMemon** [comment]
> I believe you have null rows which get displayed as progress indicators, don't return null rows, that should not display that kind of animations.
> 
> JIC, here's the piece of code responsible for the behaviour:
> 
> ![image](https://user-images.githubusercontent.com/7947027/219883112-4e4bbe01-f9a4-4dce-90c9-28f2fea4f486.png)

Thanks @maxim-saplin. 

But can you add any way where we can set loader widget while loading more data as a single widget. currently If I put loader as placeholder it displays in all rows.

**Comment by maxim-saplin** [comment]
That's how stock PaginatedDataTable works, showing spinners for null rows - though I'm not sure why anybody would want it that way, just keeping it for consistency. 

In terms of loading widget, I don't think synchronous widgets need it. You can always display a placeholder in place of empty grid. Just pass in null rows. 

Or use Stack and draw smth on top of the table via Stream/Future builder or any state management you might have (e.g. Provider).

BTW, AsyncPagibatedDataTble has Error and Loading widgets as params, though this widget is built around an async data source which can have different states.
