### ISSUE TITLE
set width of each header as needed (as character of header)

### ISSUE THREAD

**Issue by Ebrahimzarei103** [maxim-saplin/data_table_2#179]
Hello, 
I want to set the width of each header based on the character of the header 
The width of each header is based on its content.
 
`Expanded(
                child: DataTable2(
                  minWidth: 180.0 * headers.length,
                  // minWidth: 600,
                  columnSpacing: 0,
                  horizontalMargin: 10,
                  smRatio: 0.1,
                  lmRatio: 1.5,
                  headingRowHeight: 40,
                  fixedColumnsColor: Colors.white,
                  dataRowColor: MaterialStateProperty.all(Colors.white),
                  headingRowColor: const MaterialStatePropertyAll(primaryColor),
                  headingTextStyle: const TextStyle(
                      fontWeight: FontWeight.bold, color: primaryColor),
                  empty: const Center(child: Text('خالی است')),
                  columns: headers
                      .mapIndexed((index, header) => DataColumn2(
                            label: Text(
                              header,
                              style: TextStyle(color: Colors.black),
                            ),
                          ))
                      .toList(),
                  rows: items
                      .map(
                        (element) => DataRow(
                            cells: element
                                .map((item) => DataCell(
                                      Center(
                                        child: Text(
                                          element[0],
                                        ),
                                      ),
                                    ))
                                .toList()),
                      )
                      .toList(),
                ),
              ),`

**Comment by maxim-saplin** [comment]
Setting column widths based on cells contents isn't planned to be done - that is a conceptual change moving away from the current approach with S, M, L and absolute column widths

**Comment by Ebrahimzarei103** [comment]
> 
So , what can i do?
I don't want to set S, M, and L for every column, I want to set the width of each column based on its content

**Comment by maxim-saplin** [comment]
1. Submit a PR with the feature you want
2. Choose a different package with required features
