### ISSUE TITLE
Scroll Bars

### ISSUE THREAD

**Issue by ghost** [maxim-saplin/data_table_2#18]
Is there a way to always show scroll bars?

**Comment by maxim-saplin** [comment]
There's no such feature at the moment

**Comment by rwjonesnet** [comment]
Ok. Thanks

**Comment by maxim-saplin** [comment]
Keeping it open, will consider adding the feature later

**Comment by MalikSamiAwan** [comment]
I have achieved this by wrapping my data table in SingleChildScrollView and than wrap that into a Scrollbar assigning same controller to both of them but the issue is when i switch from on page to other, Scrollbar gives me error, 
Here is my Code:
`Scrollbar(
      // hoverThickness: 20,
      controller: customController,
      isAlwaysShown: true,
      showTrackOnHover: true,
      scrollbarOrientation: ScrollbarOrientation.top,

      interactive: true,
      child: SingleChildScrollView(
        controller: customController,
        scrollDirection: Axis.horizontal,
        child: Container(
          height: MediaQuery.of(context).size.height*0.8,
          width: MediaQuery.of(context).size.width*1.4,
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Stack(alignment: Alignment.bottomCenter, children: [
              PaginatedDataTable2(
                // smRatio: 0.8,
                // scrollController: customController,
                showCheckboxColumn: false,
                showFirstLastButtons: true,
                horizontalMargin: 20,
                checkboxHorizontalMargin: 12,
                columnSpacing: 10,
                wrapInCard: false,
                rowsPerPage: _rowsPerPage,
                minWidth: 1500,
                fit: FlexFit.tight,
                // hidePaginator: true,
                border: TableBorder(
                  top: BorderSide(color: Colors.grey[300]!, width: 0.2),
                  bottom: BorderSide(color: Colors.grey[300]!, width: 0.2),
                  left: BorderSide(color: Colors.grey[300]!, width: 0.2),
                  right: BorderSide(color: Colors.grey[300]!, width: 0.2),
                  verticalInside: BorderSide(color: Colors.grey[300]!, width: 0.2),
                  horizontalInside: BorderSide(color: Colors.grey, width: 0.2),

                ),
                onRowsPerPageChanged: (value) {
                  // No need to wrap into setState, it will be called inside the widget
                  // and trigger rebuild
                  //setState(() {
                  _rowsPerPage = value!;
                  print(_rowsPerPage);
                  //});
                },
                initialFirstRowIndex: 0,
                onPageChanged: (rowIndex) {
                  print(rowIndex / _rowsPerPage);
                },
                sortColumnIndex: _sortColumnIndex,
                sortAscending: _sortAscending,
                controller: _controller,
                columns: _columns,
                empty: Center(
                    child: Container(
                        padding: EdgeInsets.all(20),
                        color: Colors.grey[200],
                        child: Text('No data'))),
                source: _customersDataSource,

              ),
              Positioned(bottom: 16,child: _CustomPager(_controller)),
            ]),
          ),
        ),
      ),
    );`
    

And that is the error that i face when i paginate to other page

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
Assertion failed: file:///Users/AbdulMoeed/Downloads/flutter/packages/flutter/lib/src/widgets/scrollbar.dart:321:5
(_isVertical && _isVerticalOrientation(orientation)) || (!_isVertical && !_isVerticalOrientation(orientation))
"The given ScrollbarOrientation: ScrollbarOrientation.top is incompatible with the current AxisDirection: AxisDirection.down."


Could you help me with that please

**Comment by MalikSamiAwan** [comment]
DataTable2 built: 0ms

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
Assertion failed: file:///Users/AbdulMoeed/Downloads/flutter/packages/flutter/lib/src/widgets/scrollbar.dart:321:5
(_isVertical && _isVerticalOrientation(orientation)) || (!_isVertical && !_isVerticalOrientation(orientation))
"The given ScrollbarOrientation: ScrollbarOrientation.top is incompatible with the current AxisDirection: AxisDirection.down."

The relevant error-causing widget was: 
  Scrollbar Scrollbar:file:///Users/AbdulMoeed/Downloads/flutter-frontend-master/lib/widgets/customer_paginated_table.dart:140:12
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/flutter/src/widgets/scrollbar.dart 321:113                           [_debugAssertIsValidOrientation]
packages/flutter/src/widgets/scrollbar.dart 409:5                             [_paintScrollbar]
packages/flutter/src/widgets/scrollbar.dart 561:12                            paint
packages/flutter/src/rendering/custom_paint.dart 563:12                       [_paintWithPainter]
packages/flutter/src/rendering/custom_paint.dart 610:7                        paint
packages/flutter/src/rendering/object.dart 2409:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                          paint
packages/flutter/src/rendering/object.dart 2409:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                          paint
packages/flutter/src/rendering/object.dart 2409:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                          paint
packages/flutter/src/rendering/object.dart 2409:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                          paint
packages/flutter/src/rendering/object.dart 2409:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 141:10                             _repaintCompositedChild
packages/flutter/src/rendering/object.dart 100:5                              repaintCompositedChild
packages/flutter/src/rendering/object.dart 979:29                             flushPaint
packages/flutter/src/rendering/binding.dart 455:19                            drawFrame
packages/flutter/src/widgets/binding.dart 883:13                              drawFrame
packages/flutter/src/rendering/binding.dart 319:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1143:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1080:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 996:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1003:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 157:5                             invokeOnDrawFrame
lib/_engine/engine.dart 440:45                                                <fn>
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#b2df9 relayoutBoundary=up29
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=1128.0, 0.0<=h<=Infinity)
...  size: Size(1128.0, 576.8)
RenderObject: RenderCustomPaint#b2df9 relayoutBoundary=up29
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=1128.0, 0.0<=h<=Infinity)
  size: Size(1128.0, 576.8)
...  child: RenderRepaintBoundary#ed4c7 relayoutBoundary=up30
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=1128.0, 0.0<=h<=Infinity)
...    layer: OffsetLayer#196b6
...      engine layer: OffsetEngineLayer#21c49
...      handles: 2
...      offset: Offset(0.0, 0.0)
...    size: Size(1128.0, 576.8)
...    metrics: 87.5% useful (1 bad vs 7 good)
...    diagnosis: this is a useful repaint boundary and should be kept
...    child: _RenderScrollSemantics#56bbe relayoutBoundary=up31
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=1128.0, 0.0<=h<=Infinity)
...      semantic boundary
...      size: Size(1128.0, 576.8)
...      child: RenderPointerListener#2c65f relayoutBoundary=up32
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=1128.0, 0.0<=h<=Infinity)
...        size: Size(1128.0, 576.8)
...        behavior: deferToChild
...        listeners: signal
...        child: RenderSemanticsGestureHandler#a9d9a relayoutBoundary=up33
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=1128.0, 0.0<=h<=Infinity)
...          size: Size(1128.0, 576.8)
...          behavior: opaque
...          gestures: horizontal scroll
====================================================================================================

**Comment by MalikSamiAwan** [comment]
<img width="1280" alt="Screenshot 2021-11-12 at 4 13 59 AM" src="https://user-images.githubusercontent.com/28738729/141382297-4d569860-d4cb-43be-9fcc-73f6c9ebe39a.png">

**Comment by MalikSamiAwan** [comment]
with above code i do have a scrollbar visible horizontal and datatable veritical scrollbar as well but with this error

**Comment by maxim-saplin** [comment]
@MalikSamiAwan I wouldn't put PaginatedDataTable2 or DataTable2 inside any scroll controls as it will mess with SingleChildScrollView widgets used internally. If you want to have the scrollbars visible all the time you can use the trick with themes mentioned above, e.g.:

```
Theme(
              data: ThemeData(
                  scrollbarTheme: ScrollbarThemeData(
                      isAlwaysShown: true, 
                      thumbColor:
                          MaterialStateProperty.all<Color>(Colors.black))),
              child: PaginatedDataTable2(
```

**Comment by MalikSamiAwan** [comment]
Thankyou sir, i will give it a try
