### ISSUE TITLE
is there any way to merge row in datatable2?

### ISSUE THREAD

**Issue by shyamfuturellp2022** [maxim-saplin/data_table_2#181]
Hi,
I have a requirement to merge row . I am using datatable2 . Please help me.

**Comment by maxim-saplin** [comment]
There's no capability to merge rows or columns (such as rowspan or copspan in HTML).

Though in your case you can try a workaround. E.g. if you want to merge 2 rows you can define DataRow2.specificRowHeight to be double of the height of DataTable2.headingRowHeight and add a single DataRow2 with cells containing 2 items each.

**Comment by javaone199** [comment]
rowspan/colspan are needed for real-world business data sheet. Could you keep this open so that it can be tracked?
