### ISSUE TITLE
Divider in PaginatedDataTable2

### ISSUE THREAD

**Issue by JohnKinyanjui** [maxim-saplin/data_table_2#183]
![Screenshot 2023-04-15 055345](https://user-images.githubusercontent.com/52638680/232179639-aa82decc-f61f-4d56-9ac4-acc863237e80.png)

``` dart
Theme(
                    data: Theme.of(context)
                        .copyWith(dividerColor: Colors.transparent),

```
I have been trying to remove dividers or at least reduce the thickness but nothing works and even tried Theme but still not working.Is there any solutions available?

**Comment by maxim-saplin** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/7947027/232289237-8ef3f07a-0eae-4078-9026-6f7d024a7dfd.png">

Setting DataTable2.dividerThickness does the trick. Check what can be the source of dividers in your case (e.g. borders are set to table, some borders are set in cell contexts etc.
