### ISSUE TITLE
Add Material you 3.0 style changes

### ISSUE THREAD

**Issue by fisforfaheem** [maxim-saplin/data_table_2#184]
this can help data table look cool and modern

**Comment by maxim-saplin** [comment]
Which style changes specifically?

**Comment by fisforfaheem** [comment]
First enable material 3.0 in the themes section of your project, the border colors can also be automated using material you like styles

**Comment by maxim-saplin** [comment]
Can use your help/suggestion in a form of PR. The ask is to generic

**Comment by fisforfaheem** [comment]
Sorry I am still new to GITHUB, wish I could provide more clearance.  Anyway, Can you please see the libretube UI, I know it's not a data table, but u can get to see what material 3.0 use looks like for closure. amybe
