### ISSUE TITLE
Have a fixed edit button for each row

### ISSUE THREAD

**Issue by Ebrahimzarei103** [maxim-saplin/data_table_2#190]
Hello, 
Can I have an edit button for each row in my table? 
I want that edit button to be fixed and not scroll with scrolling the table horizontally

**Comment by maxim-saplin** [comment]
You can add any widget to a data cell, button included. If you want buttons to be always visible despite horizontal scrolling you can add the button to the leftmost column and have it fixed (set DataTable2.fixedLeftColumns to 1)

**Comment by yogithesymbian** [comment]
where it is for `fixedlefColumns`
```
return DataRow2.byIndex(
            index: index,
            color: colorOfRow,
            cells: List.generate(
              29,
              (index) {
                return const DataCell(
                  MouseRegion(
                    child: Text('data'),
                  ),
                );
              },
            ),
          );
```
