### ISSUE TITLE
Disable Visible  Horizontal Scrollbar on IOS

### ISSUE THREAD

**Issue by DimaOstrovskyiEk** [maxim-saplin/data_table_2#192]
No option to disable the visible horizontal scrollbar on IOS with DataTable2

**Comment by maxim-saplin** [comment]
https://github.com/maxim-saplin/data_table_2/issues/140#issuecomment-1255413900

**Comment by DimaOstrovskyiEk** [comment]
@maxim-saplin I tried to play with themes. On android this managed to disable horizontal scrolling, but not on IOS.

**Comment by maxim-saplin** [comment]
There're actually plenty of scroll views with scrollbars and scroll configurations which are there to mae fixed cols/rows happen and frankly speaking it is the part I was always affraid of to touch... I don't think the approach of surfacing some property will be a good approach for all use cases. I beleive themes should work and they worked on most platforms, except iOS... Need some time to look closer at what's in the code

**Comment by maxim-saplin** [comment]
For the record, Scrollbar internally picked to use either Material or Cupertino scrollbar, the letter one ignores style: https://github.com/flutter/flutter/issues/36603

**Comment by maxim-saplin** [comment]
@DimaOstrovskyiEk could you please check master channel, I've added fixes that:
- Allow to control visibility of vertical/horizontal scrollbars via DataTable2 constructor params
- Make scrollbar themes work at iOS (at least partially, covering visibility and thickness)

**Comment by DimaOstrovskyiEk** [comment]
@maxim-saplin Great news! Thanks for the quick response.

**Comment by DimaOstrovskyiEk** [comment]
@maxim-saplin Do I need to wait a bit for the changes to appear on [pub.dev](https://pub.dev/packages/data_table_2/changelog)?

**Comment by maxim-saplin** [comment]
Haven't published yet, try referencig githih from pobdev directly

**Comment by maxim-saplin** [comment]
Pushed to pub.dev
