### ISSUE TITLE
How to calculate minWidth for DataTable2 widget?

### ISSUE THREAD

**Issue by enm10k** [maxim-saplin/data_table_2#195]
I am using DataTable2 as demonstrated in the following repository, but I encountered an assertion error.
Could you please guide me on how to calculate minWidth for DataTable2 widget?

## Repository

https://github.com/enm10k/flutter_data_table_2_min_width_problem/blob/main/lib/main.dart

- There are six DataColumn2 widgets with fixedWidth set to 140. 
- minWidth for the DataTable2 widget is set to 840, calculated as 140 multiplied by 6.

## Assertion

```
# Since I have added some code to output variables as follows for debugging in data_table_2, the line numbers displayed in the following stack trace may not be accurate.

# variables in data_table_2
I/flutter (16485): DataTable2 built: 2ms
I/flutter (16485): DEBUG: checkBoxWidth: 0.0
I/flutter (16485): DEBUG: totalFixedWidth: 840.0
I/flutter (16485): DEBUG: totalColAvailableWidth: 792.0

======== Exception caught by widgets library =======================================================
The following assertion was thrown building SyncedScrollControllers(dirty, state: SyncedScrollControllersState#975be):
DataTable2, combined width of columns of fixed width is greater than availble parent width. Table will be clipped.
'package:data_table_2/src/data_table_2.dart':
Failed assertion: line 1183 pos 12: 'totalFixedWidth < totalColAvailableWidth'
``

**Comment by maxim-saplin** [comment]
Aassertuon means it's warning,  it should be running fine in release mode. What youbget is an error saying that the combined width of all rows is greater than available width. You can set on of the columns to relative size, so that it gets resized

**Comment by enm10k** [comment]
Thank you for your response.

Here is what I was expecting:

- Make all the columns the same width
- By setting a minWidth to the DataTable2 widget, totalColAvailableWidth would be the same as the minWidth

I will try to understand the current logic when I have time.
