### ISSUE TITLE
Can't change header checkbox border color

### ISSUE THREAD

**Issue by Shehzad1Dev** [maxim-saplin/data_table_2#199]
- Actually, I have change header row color using this property
```
 headingRowColor: MaterialStateColor.resolveWith((states) => Colors.black),
``` 
- It's working 
- But at the same time, I'm unable to change the checkbox border color in header row. I want to make its border and background color white.

![image](https://github.com/maxim-saplin/data_table_2/assets/121786378/1e06f5c0-a239-40fd-8664-2b039b4550eb)

- How Can I do that?

**Comment by maxim-saplin** [comment]
Pushed to pub.dev
