### ISSUE TITLE
Paging support in the datasource.

### ISSUE THREAD

**Issue by Josua2012** [maxim-saplin/data_table_2#20]
Hi,
It would be very interesting if the datasource had paging support, in this way it would not have to take all the records from the server, which would not be very correct when there are huge amounts of records.
This would be similar to what the Advanced_datatable (https://pub.dev/packages/advanced_datatable) widget does. 
Thanks.
Regards,
Jose

**Comment by maxim-saplin** [comment]
I beleve you are talking of asynchronous data fetching. In this case you can use DataTable2, create custom paginator and use whatever data fetching and state management approach you might want. Here's an example: https://github.com/maxim-saplin/flutter_web_spa_sample

Besides there's a pending pool request reagrding adding support for an AsyncDataSource to deal with asyn data loads inside PaginatedDataTable2: https://github.com/maxim-saplin/data_table_2/pull/19 - out-of-the-box async API that will allow PaginatedDataTable2 to load pages form the server is upcoming.

**Comment by Josua2012** [comment]
Hi Maxim,
When the component allows asynchronous data fetching, the auto rowsPerPage functions based on the height of the PaginatedDataTable and more customization options will be the most powerful component for displaying data tables. 🥇 
Thank you very much for all your work. 
Regards,

**Comment by Josua2012** [comment]
Any estimated date for the inclusion of this functionality in the widget? 
Thanks.

**Comment by maxim-saplin** [comment]
I've started working on the auto page rows last week, hope to have it done this week. No ETA on async data source pull request at the moment

**Comment by Josua2012** [comment]
Thanks Maxim.
