### ISSUE TITLE
specificRowHeight of DataRow2 does not work properly in AsyncDataTableSource

### ISSUE THREAD

**Issue by khwgit** [maxim-saplin/data_table_2#205]
https://github.com/maxim-saplin/data_table_2/blob/c9c88feabc64f1af2e06d7fb9940f20abc95247d/lib/src/async_paginated_data_table_2.dart#L71-L81

In the clone method of `AsyncDataTableSource`, 
`specificRowHeight` is not copied, which will reset it to the default height when the row is selected.

**Comment by maxim-saplin** [comment]
Fixed and pushed to pub.dev.
