### ISSUE TITLE
availableRowsPerPage cannot be seen macOS

### ISSUE THREAD

**Issue by MichalNemec** [maxim-saplin/data_table_2#206]
Hello,
i have availableRowsPerPage set to 10, 20, 50, 100
But i cannot see it, tried safearea + scaffold
<img width="214" alt="image" src="https://github.com/maxim-saplin/data_table_2/assets/5663019/19a87e5f-ba61-4eb0-bf78-2c783129e403">

How can this be fixed?

**Comment by maxim-saplin** [comment]
Row per page automatically hides all values that are smaller than the total number of available rows. I.e. if you have 19 rows than the page can't be 20.
