### ISSUE TITLE
Internationalization of texts

### ISSUE THREAD

**Issue by Josua2012** [maxim-saplin/data_table_2#21]
Hi,
Is there a way to change the language of the PaginatedDataTable2 texts?
For example the text of Rows per page. 
Thanks.
Regards,
Jose

**Comment by maxim-saplin** [comment]
Hi,

Loclization is supported and works exactly as in stock widgets. You can try this by chaging the sample in the following way:

1. Add localization de[endency to pubspec.yaml
```
  flutter_localizations:
    sdk: flutter
```
2. Add 2 properties to MaterialApp in main.dart
```
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en', ''),
        const Locale('be', ''),
        const Locale('ru', ''),
      ],
      locale: Locale('ru', ''),
```
3. See that paginated table controls are translated:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/7947027/123559233-75be9f00-d7a3-11eb-89fe-16da51b8b3ea.png">
