### ISSUE TITLE
DataTable 2 inside ScrollView (ListView, SingleSchildScrollView)

### ISSUE THREAD

**Issue by DimaOstrovskyiEk** [maxim-saplin/data_table_2#213]
When we have a large enough list and it does not fit on the screen, internal scrolling of the list is triggered, but when we reach the end of the list, the overall scrolling of the screen does not work.

**Comment by maxim-saplin** [comment]
![Screenshot_20230814_173709_Firefox Nightly](https://github.com/maxim-saplin/data_table_2/assets/7947027/c86ceb4c-473e-43fb-b7a7-d2f01c1e7893)

**Comment by DimaOstrovskyiEk** [comment]
My widget 'DataTable 2' has static height and is inside the column. The column itself is inside ListView. @maxim-saplin

**Comment by DimaOstrovskyiEk** [comment]
Hello, @maxim-saplin Please see an example of my problem and one of the solutions taken from the overflow stack. Perhaps you have other ideas about this.
