### ISSUE TITLE
My DataTable2 does not make fixed header in table

### ISSUE THREAD

**Issue by snorliman** [maxim-saplin/data_table_2#22]
can You help me with this ? this my code :

import 'package:data_table_2/data_table_2.dart';
`showTable(List<Product> data, isWide, loading, screenWidth) {
    return FadeTransition(
      opacity: tableController,
      child: TweenAnimationBuilder(
        tween: scaleTween,
        duration: Duration(milliseconds: tableDuration),
        builder: (context, double scale, child) {
          return Transform.scale(
            scale: scale,
            child: child,
          );
        },
        child: Card(
          color: tableCardColor,
          elevation: 15,
          child: Container(
            height: isWide ? 149 : 180,
            child: ScrollConfiguration(
              behavior: ScrollConfiguration.of(context).copyWith(dragDevices: {
                PointerDeviceKind.touch,
                PointerDeviceKind.mouse,
              }),
              child: SingleChildScrollView(
                controller: scrollController,
                scrollDirection: Axis.horizontal,
                child: SingleChildScrollView(
                  child: ConstrainedBox(
                    constraints: BoxConstraints(
                        minWidth: screenWidth * 0.8,
                        maxWidth: screenWidth * 0.8),
                    child: DataTable2(
                        columnSpacing: 12,
                        minWidth: 600,
                        smRatio: 0.75,
                        lmRatio: 1.5,
                        dataTextStyle: TextStyle(
                            fontSize: isWide ? 13 : 12, color: Colors.black),
                        decoration: dataTableDecoraiton(),
                        columns: [
                          DataColumn2(
                              size: ColumnSize.S,
                              label: Text('Seria',
                                  style:
                                      TextStyle(fontWeight: FontWeight.bold))),
                          DataColumn2(
                              size: ColumnSize.S,
                              label: Text('Indeks',
                                  style:
                                      TextStyle(fontWeight: FontWeight.bold))),
                          DataColumn2(
                              size: ColumnSize.S,
                              label: Text('Nazwa części',
                                  style:
                                      TextStyle(fontWeight: FontWeight.bold))),
                          DataColumn2(
                              size: ColumnSize.S,
                              label: Text('Firma',
                                  style:
                                      TextStyle(fontWeight: FontWeight.bold))),
                          DataColumn2(
                              size: ColumnSize.S,
                              label: Text('Ostatnia zmiana statusu',
                                  style:
                                      TextStyle(fontWeight: FontWeight.bold))),
                        ],
                        rows: data
                            .map((product) => DataRow(
                                    selected: selectedProduct.contains(product),
                                    onSelectChanged: (isSelected) {
                                      setState(() {
                                        selectedProduct = [];
                                        final isAdded =
                                            isSelected != null && isSelected;
                                        isAdded
                                            ? selectedProduct.add(product)
                                            : selectedProduct
                                                .remove(product.productSerial);
                                      });
                                    },
                                    color: dataTableColor(),
                                    cells: [
                                      DataCell(Text(product.productSerial)),
                                      DataCell(Text(product.productIndex)),
                                      DataCell(Text(product.productName)),
                                      DataCell(Text(product.companyName)),
                                      DataCell(
                                          Text(product.daysAgo.toString())),
                                    ]))
                            .toList()),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }`

**Comment by maxim-saplin** [comment]
OK)
