### ISSUE TITLE
Can this perfrom curd opertaion if all the datacells have and TextFormField

### ISSUE THREAD

**Issue by Tushar474** [maxim-saplin/data_table_2#228]
`Future<AllroundsNotifier> fetchAllData(
      AllroundsNotifier allroundsNotifier) async {
    String URL =
        "https://admin.trackblazerssportsacademy.com/score/score-panel-app";
    try {
      if (!isCalled) {
        http.Response response = await http.get(
          Uri.parse(
            URL,
          ),
        );
        if (response.statusCode == 200) {
          var result = jsonDecode(response.body);
          mainAllrounds = AllRoundsList.fromJson(result);
          allroundsNotifier.setData(mainAllrounds);
          // roundlist = result['data'];
          // print(mainAllrounds.data.length);
        }
        rows.clear();
        for (int i = 0; i < mainAllrounds.data.length; i++) {
          Map<String, String> concatenatedValues = {};
          List<int> rowIds = []; // Initialize an empty list

          for (String cell in dataCells) {
            final cellValue = mainAllrounds.data[i].toJson()[cell];
            concatenatedValues[cell] = '$cellValue';
            textEditingControllerMap[cell] =
                TextEditingController(text: '$cellValue'.toString());
            List<Map<String, dynamic>> rowsData = [];
          }
          rows.add(DataRow(
            cells: [
              DataCell(
                Column(
                  children: [
                    Padding(
                        padding: const EdgeInsets.all(15.0),
                        child: Text(mainAllrounds.data[i].id.toString())),
                  ],
                ),
              ),
              DataCell(
                Column(
                  children: [
                    Padding(
                      padding: const EdgeInsets.all(15.0),
                      child: Text(
                        "${mainAllrounds.data[i].fname} ${mainAllrounds.data[i].lname}",
                      ),
                    ),
                  ],
                ),
              ),
              for (String cell in dataCells)
              DataCell(Row(
                  children: [
                    Expanded(
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: TextFormField(
                          // initialValue: concatenatedValues[cell] ?? '',
                          controller: textEditingControllerMap[cell],
                          onChanged: (newValue) async {
                            isCalled = true;
                            textEditingControllerMap[cell]?.text = newValue.toString();
                            final row = {
                              TsaDatabase.r_1: textEditingControllerMap, // Change this to the appropriate column name
                              // Add other columns and their values as needed
                            };
                            try {
                              print(row);
                              // Code that may cause the RangeError
                              final updatedRowId = await _tsaDatabase.update(
                                  row, rowIds[i] as String);
                              // Rest of your code
                              if (updatedRowId != null) {
                                print(updatedRowId);
                                // Data was successfully updated
                                print('Data updated for row ID: $updatedRowId');
                              } else {
                                // Update failed (row with the specified ID not found)
                                print(
                                    'Data update failed for row ID: $rowIds[i]');
                              }
                            } catch (e) {
                              // Handle the error here
                              print('Error: $e');
                            }
                            },
                          decoration: const InputDecoration(
                            border: OutlineInputBorder(),
                            contentPadding: EdgeInsets.all(8.0),
                          ),
                        ),
                      ),
                    ),`
                    
                    There are error in this code i have shared but i want to know if my doubt is possible to do ?

**Comment by maxim-saplin** [comment]
I have no idea what you sre trying to say
