### ISSUE TITLE
Paging with the mouse wheel (PaginatedDataTable2)

### ISSUE THREAD

**Issue by Josua2012** [maxim-saplin/data_table_2#23]
Hi,
It would be very powerful that with the mouse wheel you could navigate between pages.
Thanks.
Regards,
Jose

**Comment by maxim-saplin** [comment]
Sorry, missed the notification... How do you see that feature exactly? Can see troubles with scrolling behaviour. E.g. scrolling down to the end of the list and then sudden change of the page can be a bad surprise/

**Comment by Josua2012** [comment]
Hi Maxim,
This should be a feature that can or cannot be connected. 
This feature can be very interesting together with the autorowsperpage feature regarding paginateddatatable2 widget height, in this way having both functionalities connected, the mouse wheel could navigate between pages, avoiding the user having to click on the buttons of previous page or page forward.
What do you think? 
Regards,
Jose

**Comment by maxim-saplin** [comment]
Frankly speaking I don't see the feature in such detail so it is not confusing for users.

**Comment by Josua2012** [comment]
I think that it is not at all confusing for users. Having support for the mouse wheel you can see the rows of the pages in a very easy way without having to click on the bottom buttons of the paginateddatatable2.
This is how most desktop paginated grids work.
Check out the following video: https://recordit.co/6pLn9eSK3M
As you will see, it is much faster to navigate between the pages and find any record you are looking for than to use the buttons below. :)

**Comment by maxim-saplin** [comment]
In short the idea is to allow switching page numbers with mouse scrolling up or down. To my taste that is not the best UI/UX approach, scrolling is typically associated smoth motion of list items, rather then jumps from one list to another. Virtual scrolling (which is currently not present) seems like a better practice. I would refrain from adding this feature to the widget at the moment.
Though it makes sense to have a capability for developers to externaly control the current page number or page size via some sort of controller just to allow custom implementation of the feature like you desribed or any other one might come up with.

**Comment by Josua2012** [comment]
Ok. Thanks Maxim.
