### ISSUE TITLE
DataTable2 in full scrollable page

### ISSUE THREAD

**Issue by herna** [maxim-saplin/data_table_2#236]
Hi,

I am trying to build a page where I have some search options at the top and the results table below them. The result I'm looking for is something like this:

https://github.com/maxim-saplin/data_table_2/assets/3002441/ef6820d1-be37-4815-8415-1161abecf988

Since I cannot put `DataTable2` inside `SingleChildScrollView`, how can I achieve this? I was trying different combinations but the layout always breaks.

Could you please @maxim-saplin let me know something about this? I can't get it to work.

Thank you

**Comment by maxim-saplin** [comment]
Try putting it in a size box first and limiting the height
