### ISSUE TITLE
Gray space in release mode

### ISSUE THREAD

**Issue by 9KevDev** [maxim-saplin/data_table_2#238]
I wrapped data_table_2 with Expanded() and put them inside Column(). When I run app on release mode. Widget will turn to gray bloc. But it work fine on debug mode.

**Comment by maxim-saplin** [comment]
Check the debug output and see what layout problem you have there. If you still consider that your widget structure is fine and DataTable2 is not working OK, please provide `flutter doctor' output and attach a minimal repro example

**Comment by 9KevDev** [comment]
It work perfectly in debug mode. Just only happen when I build the apk and install it in real phone or other android emulator like LDPlayer. My flutter doctor is OK all green checked. I'm trying to create a new public repo and tracking the issue. I will let you know if I fond more info in this. Thank you for your quick response.

**Comment by maxim-saplin** [comment]
Did you check the "Debug" pane in VSCode (or whatever is the IDE you are using). What I mean by checking the bedbug output is running the app and checking what kind of messages are there. It is a known behaviour of Flutter when it will display the UI in Debug mode, while there're some errors(e.g. widget layout errors) and the same app will have grey view when run in Release mode until those errors are fixed.

**Comment by 9KevDev** [comment]
@maxim-saplin You are right there is a issue in app before render the data_table_2 (not related to data_table_2 widget). After fixed this issue, data_table_2 is display perfectly on run build APK. Sorry for wrong issue report.
