### ISSUE TITLE
hover on all row

### ISSUE THREAD

**Issue by wepashka** [maxim-saplin/data_table_2#239]
When hovering over a cell, I want all cells in the corresponding row to exhibit a hover effect

**Comment by maxim-saplin** [comment]
?

**Comment by wepashka** [comment]
Can I have the entire corresponding row highlight when I hover over a cell?

**Comment by maxim-saplin** [comment]
https://maxim-saplin.github.io/data_table_2/#/datatable2 

It is the current default behaviour, as long as you don't have tap event handlers on individual cells

**Comment by wepashka** [comment]
Thanks I was using old version of this package.
