### ISSUE TITLE
A AsyncDataTableSource was used after being disposed.

### ISSUE THREAD

**Issue by jtrepagne** [maxim-saplin/data_table_2#241]
Hello !

I've been enjoying the use of this package lately, it's working great for my async paginated datatables requirements.

Today I experienced an issue on my Windows app. It is related to the removal of datatables (ie: leaving the current GoRouter page) while they are performing async tasks (like fetching new rows on datatable page change). They call methods such as `notifyListeners` but since the AsyncDataTableSource class has been disposed, it fails. Here is the error message : 
```
A DTBusinessDataSourceAsync was used after being disposed.
Once you have called dispose() on a DTBusinessDataSourceAsync, it can no longer be used.
```
The line of code throwing the exception is `async_paginated_data_table_2.dart:262`

Since Im pretty new with Flutter, I'm not sure of the best approach to solve this, should it be a package fix, a guideline highlight in the documentation or better practices in my projetct (regarding Flutter and data_table_2)

For now I fixed it by overriding several methods of my custom datasource class :
```dart
  @override
  void dispose() {
    _disposed = true;

    super.dispose();
  }

  @override
  void notifyListeners() {
    if(!_disposed) {
      super.notifyListeners();
    }
  }
```

Thanks for your time

**Comment by maxim-saplin** [comment]
I think you have solved the issues by properly managing lifecycle of the datasource and implementing dispose method - which seems reasonable

**Comment by stan-at-work** [comment]
@maxim-saplin I managed to fix it by changing the source in: 'data_table_2-2.5.9\lib\src\paginated_data_table_2.dart'

...
`
/// Holds the state of a [PaginatedDataTable2].
///
/// The table can be programmatically paged using the [pageTo] method.
class PaginatedDataTable2State extends State<PaginatedDataTable2> {
  late int _firstRowIndex;
  late int _rowCount;
  late bool _rowCountApproximate;
  int _selectedRowCount = 0;
  final Map<int, DataRow?> _rows = <int, DataRow?>{};
  int _effectiveRowsPerPage = -1;
  int _prevRowsPerPageForAutoRows = -1;

  //* NEW
  bool disposed = false;

  @override
  void setState(VoidCallback fn) {
    if (disposed) return;
    // Notifying listeners in the next message queue pass
    // Doing that in the current call somehow messes with update
    // lifecycle when using async table
    if (widget.controller != null) {
      Future.delayed(const Duration(milliseconds: 0), () => widget.controller?._notifyListeners());
    }
    //widget.controller?._notifyListeners();
    super.setState(fn);
  }

  @override
  void initState() {
    super.initState();
    _firstRowIndex = PageStorage.of(context).readState(context) as int? ?? widget.initialFirstRowIndex ?? 0;
    widget.source.addListener(_handleDataSourceChanged);
    _effectiveRowsPerPage = widget.rowsPerPage;
    widget.controller?._attach(this);
    _handleDataSourceChanged();
  }

  @override
  void didUpdateWidget(PaginatedDataTable2 oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (disposed) return;
    if (oldWidget.source != widget.source) {
      oldWidget.source.removeListener(_handleDataSourceChanged);
      widget.source.addListener(_handleDataSourceChanged);
      _handleDataSourceChanged();
    }
    if (oldWidget.controller != widget.controller) {
      oldWidget.controller?._detach();
      widget.controller?._attach(this);
    }
  }

  @override
  void dispose() {
    widget.source.removeListener(_handleDataSourceChanged);
    disposed = true;
    super.dispose();
  }

...`

**Comment by maxim-saplin** [comment]
I am not sure I understand you.

In the first message you say you have an exception since the datasource you give to the table is in wrong state (disposed). And you work this around  by somehow managing the cycle of whatever widget structure you have.

In the second message you show some snippet which checks if widget (and not a datasource) is disposed...

In summary I don't understand what is the issue and how is it related to this package. If you can provide a minimal reproduction example which demonstrates the issues - I am happy to look into it. The disconnected pieces of info you have shared so far don't help

**Comment by jtrepagne** [comment]
I think there's some confusion...

@stan-at-work If you look at the core implementation, you got to implement your own datasource by extending a DataTableSource. There, you can override the dispose method. Then, your datatable can consume it.

Here's an example :
```dart
class AppDataSourceAsync extends AsyncDataTableSource {
  // ...

  bool _disposed = false;
  
  // ...

  @override
  void dispose() {
    _disposed = true;

    super.dispose();
  }

  @override
  void notifyListeners() {
    if(!_disposed) {
      super.notifyListeners();
    }
  }
  
  // ...
}
```
