### ISSUE TITLE
Horizontal scroll issue

### ISSUE THREAD

**Issue by crazycoder534** [maxim-saplin/data_table_2#242]
data in cells and columns are in multiline due to table try to to display itself on page without horizontal scroll.
if i don't provide minWidth then unable to scroll horizontally.
i want to adjust the columns  and rows width according to values in it and also make it horizontal scrollable.

**Comment by maxim-saplin** [comment]
No idea what the problem is... Please explain and demonstrate, ideally with a small repro issue
