### ISSUE TITLE
Horizontal Scroll Bar Issue

### ISSUE THREAD

**Issue by aaronlee145** [maxim-saplin/data_table_2#243]
Hello,

The horizontal scroll bar appears randomly when resizing the screen, even when it should not be scrollable horizontally. 

Can this horizontal scroll bar be disabled? Thanks

**Comment by maxim-saplin** [comment]
https://pub.dev/documentation/data_table_2/latest/data_table_2/DataTable2/isHorizontalScrollBarVisible.html

**Comment by aaronlee145** [comment]
Thanks, I have tried it before, but it still appears when i hover on the table. Can i disable it completely? Thanks a lot

**Comment by maxim-saplin** [comment]
Try playing with scroll bar theming
```
return Theme(
        data: ThemeData(
            scrollbarTheme: ScrollbarThemeData(
                thumbVisibility: ...
                thumbColor: ...
        child: DataTable2(
```

**Comment by aaronlee145** [comment]
I want to keep the vertical scroll bar, but with scroll bar theme I cannot have separate theme for vertical/ horizontal scroll bar.

Will stick with isHorizontalScrollBarVisible for now if it cannot be completely disabled. 

Thanks again
