### ISSUE TITLE
[Question] How to customize a Row and the Divider between rows ?

### ISSUE THREAD

**Issue by fvisticot** [maxim-saplin/data_table_2#245]
I need to implement the following design (custom Row + Spacing between rows). Is it possible with data_table_2 ?

<img width="841" alt="Capture d’écran 2023-12-26 à 22 51 09" src="https://github.com/maxim-saplin/data_table_2/assets/153679/570fd690-cfad-495f-b238-9c26808e947f">

**Comment by maxim-saplin** [comment]
@fvisticot, you can try recreating something similar via `DataRow2.decoration`, check examples (`data_table2_rounded.dart`):

<img width="1065" alt="image" src="https://github.com/maxim-saplin/data_table_2/assets/7947027/8e1a5686-b975-4f07-b28e-9695b10ba088">

**Comment by fvisticot** [comment]
I have checked and it works fine. 
Tx for this updarte
