### ISSUE TITLE
I need overLay Component in AsycDataTable

### ISSUE THREAD

**Issue by SettiNitesh** [maxim-saplin/data_table_2#248]
https://github.com/maxim-saplin/data_table_2/assets/118504481/93c8dd42-b3db-400c-bfda-2ff4f4294441

I need data to be persist there when i am calling get api after post or put rather than showing empty layout .On top of data i need to see loader like how sort is happening like that I need .

**Comment by SettiNitesh** [comment]
How to implement that functionality
@maxim-saplin  bocz I am unable to find .

**Comment by maxim-saplin** [comment]
Did I get you right that you need to display the old rows faded behind the spinner?
