### ISSUE TITLE
Add option for hiding pagination for one page

### ISSUE THREAD

**Issue by javaone199** [maxim-saplin/data_table_2#250]
Add option for hiding pagination for one page. For example, sales order lines are shown in one page, and no need for pagination.

Solution: allow rowsPerPage to be nullable ( int? ). If null, hide the pagination.

**Comment by maxim-saplin** [comment]
You can use [hidePaginator](https://pub.dev/documentation/data_table_2/latest/data_table_2/PaginatedDataTable2/hidePaginator.html) and rebuild the widget
