### ISSUE TITLE
Hide empty rows

### ISSUE THREAD

**Issue by javaone199** [maxim-saplin/data_table_2#251]
PaginatedDataTable2(
        renderEmptyRowsInTheEnd: false,
        ...
);

If rowsPerPage is 20, and the last page has 10 data rows, there will be 10 empty rows in the last page. Add an option for removing the empty rows. For mobile device like iphone,
having so much blank space is not ideal. It is ok to expand/shrink the table height while paginating.

PaginatedDataTable2(
        renderEmptyRowsInTheEnd: false,
        hideEmptyRowsInTheEnd: true,
        ...
        rowsPerPage: 20,
);

**Comment by maxim-saplin** [comment]
Don't get it

**Comment by javaone199** [comment]
Hide the empty rows. Currently it has a blank space if rowsPerPage is 20, and the last page has one item only. Thanks.

**Comment by fedser** [comment]
@javaone199  you should to set `renderEmptyRowsInTheEnd=false` to achieve what you want.
