### ISSUE TITLE
isHorizontalScrollBarVisible & isVerticalScrollBarVisible for AsyncPaginatedDataTable2

### ISSUE THREAD

**Issue by TarishAhmed** [maxim-saplin/data_table_2#257]
The DataTable2 have the option to show the horizontal and vertical scrollbar letting the user know there is content of the data table that is hidden from the flow and would require a scroll to view, and since AsyncPaginatedDataTable2 does not have this, this table however being much much efficient than DataTable2 for every other task, becomes harder to adopt.

**Comment by GuHiroo** [comment]
PaginatedDataTable2 wants the same.
Have tried this but nothing about track valid.

`Theme(
        data: ThemeData(
            scrollbarTheme: ScrollbarThemeData(
              thumbColor: MaterialStateProperty.all(Colors.orange),
              trackColor: MaterialStateProperty.all(Colors.orange),
              trackVisibility: MaterialStateProperty.all(true),
            )),
        child: PaginatedDataTable2(...`

**Comment by GuHiroo** [comment]
> The DataTable2 have the option to show the horizontal and vertical scrollbar letting the user know there is content of the data table that is hidden from the flow and would require a scroll to view, and since AsyncPaginatedDataTable2 does not have this, this table however being much much efficient than DataTable2 for every other task, becomes harder to adopt.

Hello, I've tried this and it works well for paginateddatatable2 and async one.

`Theme(
        data: ThemeData(
            scrollbarTheme: ScrollbarThemeData(
              thumbVisibility: MaterialStateProperty.all(true),
            )),
        child: PaginatedDataTable2(...`

**Comment by TarishAhmed** [comment]
@GuHiroo this works perfectly, thank you

**Comment by TarishAhmed** [comment]
@maxim-saplin could you review this https://github.com/maxim-saplin/data_table_2/pull/261

**Comment by maxim-saplin** [comment]
Fixed in 2.5.11 and pushed to pub.dev. Thx to @TarishAhmed
