### ISSUE TITLE
switch off print that show building time of datatable 

### ISSUE THREAD

**Issue by snorliman** [maxim-saplin/data_table_2#26]
Where is a way to switch it off?

**Comment by maxim-saplin** [comment]
Those trace messages don't have a switch. Do they create trouble?

**Comment by snorliman** [comment]
ok:) thank you for quick answer:) it's not big deal but i was curios about that, if there is no way to disable this I have to use to it:) have nice day:)

**Comment by maxim-saplin** [comment]
I can make the change to the code, no big deal) I just found it useful when optimizing the UI and catching excessive rebuilds and slow cases. Flutter's tables are not that performance (e.g. when comparing to HTML)
