### ISSUE TITLE
The provided ScrollController is currently attached to more than one ScrollPosition.

### ISSUE THREAD

**Issue by Soorya-S** [maxim-saplin/data_table_2#27]
I'm getting an exception when scrolling the data table with the mouse wheel.

`DataTable2 built: 0ms

════════ Exception caught by animation library ═════════════════════════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/flutter/src/widgets/scrollbar.dart 1255:9                                                                         <fn>
packages/flutter/src/widgets/scrollbar.dart 1278:14                                                                        [_debugCheckHasValidScrollPosition]
packages/flutter/src/widgets/scrollbar.dart 1197:14                                                                        [_validateInteractions]
packages/flutter/src/animation/listener_helpers.dart 233:27                                                                notifyStatusListeners
packages/flutter/src/animation/animation_controller.dart 814:7                                                             [_checkStatusChanged]
packages/flutter/src/animation/animation_controller.dart 748:5                                                             [_startSimulation]
packages/flutter/src/animation/animation_controller.dart 611:12                                                            [_animateToInternal]
packages/flutter/src/animation/animation_controller.dart 495:12                                                            reverse
packages/flutter/src/widgets/scrollbar.dart 1349:37                                                                        <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19       internalCallback
The AnimationController notifying status listeners was: AnimationController#a0dba(◀ 1.000)
════════════════════════════════════════════════════════════════════════════════════════════════════`

**Comment by maxim-saplin** [comment]
Could you please provide code example/repo with reproducible issues. Also more descriptive info is needed (steps to reproduce, platform, flutter version etc.)

**Comment by MCOfficer** [comment]
Same issue here - in my case it was because i had another `ListView` next to the table, apparently they both tried to use the same `ScrollController`. Giving the table its own controller was all that was needed:
```dart
DataTable2(
    scrollController: ScrollController(),
    ...
)
```
