### ISSUE TITLE
DataCell onTap is slow / laggy

### ISSUE THREAD

**Issue by Dario-Ciceri** [maxim-saplin/data_table_2#277]
Hello, onTap is a bit slow (probably waiting for onDoubleTap?). 
onTap works fine on DataRow and on DataCell with DataTable, but with DataTable2 onTap on DataCell is a bit slow.
Any suggestions? thanks!

**Comment by maxim-saplin** [comment]
You can try disabling the data cel events and wrapping cell content into gesture detector an see if it helps

**Comment by matteo-convert** [comment]
@maxim-saplin I i reproduce the bug it's when onDoubleTap is defined 
![image](https://github.com/user-attachments/assets/de207868-c7de-4735-9991-87cfc7f653b0)

maybe add property for control this "wait timeout" ?

**Comment by EArminjon** [comment]
onDoubleTap should not listen if not set.
