### ISSUE TITLE
Is there away to change the page programmatically?

### ISSUE THREAD

**Issue by Soorya-S** [maxim-saplin/data_table_2#28]
Why do I need this?

In my case, I added a search filter. When showing the search results, the search result fits on the first page (only a few rows will be shown).
The data table is supposed to switch to the first page because the number of rows provided to the data table is lower than the rows per page (which is a bug by the way).

**Comment by maxim-saplin** [comment]
So I assume you get empty rows displayed when filter is applied... There's currently no way to control page number that I'm aware of... There's actually an idea to create a sort of controller for the widget to allow changing it's state from outside which was discussed in a separate issue (https://github.com/maxim-saplin/data_table_2/issues/23#issuecomment-882828132).

In the meantime I can suggest you using `key` property of the widget and change it whenever a new filter is applied - this should allow reset widget's state and have the page set to 1.

**Comment by kechankrisna** [comment]
Can try https://github.com/kechankrisna/data_table_2/tree/hotfix
I have forked and updated to make change current page work. But seem the owner not yet merge, so you can try it directly from this link above.

**Comment by maxim-saplin** [comment]
The feature is available on master, veryfying all is good and should have this change (as well as few more) published to pub.dev

**Comment by maxim-saplin** [comment]
2.1.1 is on pub.dev and now allows controlling PaginatedDataTable2 state via PaginatorController
