### ISSUE TITLE
After flutter pub upgrade data_table_2 showing error

### ISSUE THREAD

**Issue by RanenduKarmakar1997** [maxim-saplin/data_table_2#284]
I am using data_table_2-2.5.15. After running the `flutter pub upgrade` command and then executing the `main.dart` file for Flutter web, I encounter the following issue and it's not allow me to run the project.

Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:90:5:
Error: Type 'WidgetStateProperty' not found.
    WidgetStateProperty<Color?>? color,
    ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:362:16:
Error: Type 'WidgetStateProperty' not found.
      required WidgetStateProperty<Color?>? overlayColor,
               ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:419:16:
Error: Type 'WidgetStateProperty' not found.
      required WidgetStateProperty<Color?>? overlayColor}) {
               ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:491:16:
Error: Type 'WidgetStateProperty' not found.
      required WidgetStateProperty<Color?>? overlayColor}) {
               ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1161:7:
Error: Type 'WidgetStateProperty' not found.
      WidgetStateProperty<Color?>? effectiveDataRowColor) {
      ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1329:7:
Error: Type 'WidgetStateProperty' not found.
      WidgetStateProperty<Color?>? effectiveDataRowColor,
      ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1333:7:
Error: Type 'WidgetStateProperty' not found.
      WidgetStateProperty<Color?> defaultRowColor,
      ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1399:7:
Error: Type 'WidgetStateProperty' not found.
      WidgetStateProperty<Color?>? effectiveHeadingRowColor, int numberOfCols) {
      ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/paginated_data_table_2.dart:350:9:
Error: Type 'WidgetStateProperty' not found.
  final WidgetStateProperty<Color?>? headingRowColor;
        ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/get-4.6.5/lib/get_navigation/src/nav2/get_information_parser.dart:29:50:
Warning: Operand of null-aware operation '??' has type 'String' which excludes null.
    final matchResult = Get.routeTree.matchRoute(location ?? initialRoute);
                                                 ^
../../../.pub-cache/hosted/pub.dev/get-4.6.5/lib/get_navigation/src/nav2/get_router_delegate.dart:374:36:
Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
            await backUntil(config.location!, popMode: PopMode.Page);
                                   ^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:90:5:
Error: 'WidgetStateProperty' isn't a type.
    WidgetStateProperty<Color?>? color,
    ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:362:16:
Error: 'WidgetStateProperty' isn't a type.
      required WidgetStateProperty<Color?>? overlayColor,
               ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:419:16:
Error: 'WidgetStateProperty' isn't a type.
      required WidgetStateProperty<Color?>? overlayColor}) {
               ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:491:16:
Error: 'WidgetStateProperty' isn't a type.
      required WidgetStateProperty<Color?>? overlayColor}) {
               ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:590:12:
Error: 'WidgetState' isn't a type.
      (Set<WidgetState> states) {
           ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:589:29:
Error: The getter 'WidgetStateProperty' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
    final defaultRowColor = WidgetStateProperty.resolveWith(
                            ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:591:29:
Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
        if (states.contains(WidgetState.selected)) {
                            ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:659:31:
Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
                            ? WidgetStatePropertyAll(fixedColumnsColor)
                              ^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:665:31:
Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
                            ? WidgetStatePropertyAll(fixedColumnsColor)
                              ^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:679:27:
Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
                        ? WidgetStatePropertyAll(fixedColumnsColor)
                          ^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:728:31:
Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
                            ? WidgetStatePropertyAll(fixedCornerColor)
                              ^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:737:31:
Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
                            ? WidgetStatePropertyAll(fixedCornerColor)
                              ^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:743:31:
Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
                            ? WidgetStatePropertyAll(fixedCornerColor)
                              ^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1038:42:
Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
                              ?.resolve({WidgetState.hovered})
                                         ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1041:60:
Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
                      ? scrollBarTheme.thickness?.resolve({WidgetState.hovered})
                                                           ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1067:52:
Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
                                        ?.resolve({WidgetState.hovered})
                                                   ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1071:48:
Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
                                    ?.resolve({WidgetState.hovered})
                                               ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1161:7:
Error: 'WidgetStateProperty' isn't a type.
      WidgetStateProperty<Color?>? effectiveDataRowColor) {
      ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1329:7:
Error: 'WidgetStateProperty' isn't a type.
      WidgetStateProperty<Color?>? effectiveDataRowColor,
      ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1333:7:
Error: 'WidgetStateProperty' isn't a type.
      WidgetStateProperty<Color?> defaultRowColor,
      ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1350:21:
Error: 'WidgetState' isn't a type.
          final Set<WidgetState> states = <WidgetState>{
                    ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1350:44:
Error: 'WidgetState' isn't a type.
          final Set<WidgetState> states = <WidgetState>{
                                           ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1351:29:
Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
            if (isSelected) WidgetState.selected,
                            ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1352:29:
Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
            if (isDisabled) WidgetState.disabled,
                            ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1399:7:
Error: 'WidgetStateProperty' isn't a type.
      WidgetStateProperty<Color?>? effectiveHeadingRowColor, int numberOfCols) {
      ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1416:51:
Error: 'WidgetState' isn't a type.
        color: effectiveHeadingRowColor?.resolve(<WidgetState>{}),
                                                  ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/paginated_data_table_2.dart:350:9:
Error: 'WidgetStateProperty' isn't a type.
  final WidgetStateProperty<Color?>? headingRowColor;
        ^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.
  Command: /opt/hostedtoolcache/flutter/stable-3.19.6-x64/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/hostedtoolcache/flutter/stable-3.19.6-x64/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/opt/hostedtoolcache/flutter/stable-3.19.6-x64/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/c4cd48e186460b32d44585ce3c103271ab676355/ --native-null-assertions --no-source-maps -o /home/runner/work/alyf_provider/alyf_provider/.dart_tool/flutter_build/0c6592e4db503970e7f70eeafcb73b5f/app.dill --packages=.dart_tool/package_config.json --cfe-only /home/runner/work/alyf_provider/alyf_provider/.dart_tool/flutter_build/0c6592e4db503970e7f70eeafcb73b5f/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:326:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:188:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:861:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:799:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:628:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:93:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:[200](https://github.com/alyf-lab/alyf_provider/actions/runs/9482049005/job/26126106584#step:6:201):5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

**Comment by RanenduKarmakar1997** [comment]
![Screenshot from 2024-06-13 14-11-57](https://github.com/maxim-saplin/data_table_2/assets/91836693/a5d7de5a-fd66-4880-b853-b562294b5678)

**Comment by maxim-saplin** [comment]
What is your flutter version? Try upgrading flutter (`flutter upgrade`)

**Comment by RanenduKarmakar1997** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on Ubuntu 22.04.4 LTS 6.5.0-35-generic,
    locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2024.1)
[✓] VS Code (version 1.90.0)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by RanenduKarmakar1997** [comment]
@maxim-saplin I upgraded my Flutter version, but I'm still encountering the same issue.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on Ubuntu 22.04.4 LTS 6.5.0-35-generic, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2024.1)
[✓] VS Code (version 1.90.0)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by Ensonberg** [comment]
Target dart2js failed: ProcessException: Process exited abnormally:
../../.pub-cache/hosted/pub.dev/google_fonts-6.2.0/lib/src/google_fonts_base.dart:69:8:
Error: Type 'FontFeature' not found.
  List<FontFeature>? fontFeatures,
       ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:90:5:
Error: Type 'WidgetStateProperty' not found.
    WidgetStateProperty<Color?>? color,
    ^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:362:16:

**Comment by maxim-saplin** [comment]
Try upgrading flutter via `flutter upgrade` or try locking the version of the widget to the older one, e.g.
```
dependencies:
  data_table_2: 2.5.12
```

**Comment by theREMASTERED1** [comment]
Im having this exact issue atm @maxim-saplin 
this happened after I upgraded my kotlin from 1.7.10 to 1.8.10
and gradle tools from 7.3.0 to 7.4.2
my flutter is 3.19.6

**Comment by maxim-saplin** [comment]
> Im having this exact issue atm @maxim-saplin this happened after I upgraded my kotlin from 1.7.10 to 1.8.10 and gradle tools from 7.3.0 to 7.4.2 my flutter is 3.19.6



> Try upgrading flutter via `flutter upgrade` or try locking the version of the widget to the older one, e.g.
> 
> ```
> dependencies:
>   data_table_2: 2.5.12
> ```

**Comment by theREMASTERED1** [comment]
downgrade all the way to 2.3.0
