### ISSUE TITLE
Error: Type 'WidgetStateProperty' not found.

### ISSUE THREAD

**Issue by JubileusDeus** [maxim-saplin/data_table_2#291]
Hello.
I recently updated my version of data table 2 and I keep getting this error.
I use flutter 3.19.6 (Stable channel) and my project is a flutter web project.

Here is the log :

/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:90:5: Error: Type 'WidgetStateProperty' not found.
    WidgetStateProperty<Color?>? color,
    ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:362:16: Error: Type 'WidgetStateProperty' not found.
      required WidgetStateProperty<Color?>? overlayColor,
               ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:419:16: Error: Type 'WidgetStateProperty' not found.
      required WidgetStateProperty<Color?>? overlayColor}) {
               ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:491:16: Error: Type 'WidgetStateProperty' not found.
      required WidgetStateProperty<Color?>? overlayColor}) {
               ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1161:7: Error: Type 'WidgetStateProperty' not found.
      WidgetStateProperty<Color?>? effectiveDataRowColor) {
      ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1329:7: Error: Type 'WidgetStateProperty' not found.
      WidgetStateProperty<Color?>? effectiveDataRowColor,
      ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1333:7: Error: Type 'WidgetStateProperty' not found.
      WidgetStateProperty<Color?> defaultRowColor,
      ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1399:7: Error: Type 'WidgetStateProperty' not found.
      WidgetStateProperty<Color?>? effectiveHeadingRowColor, int numberOfCols) {
      ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/paginated_data_table_2.dart:350:9: Error: Type 'WidgetStateProperty' not found.
  final WidgetStateProperty<Color?>? headingRowColor;
        ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:90:5: Error: 'WidgetStateProperty' isn't a type.
    WidgetStateProperty<Color?>? color,
    ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:362:16: Error: 'WidgetStateProperty' isn't a type.
      required WidgetStateProperty<Color?>? overlayColor,
               ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:419:16: Error: 'WidgetStateProperty' isn't a type.
      required WidgetStateProperty<Color?>? overlayColor}) {
               ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:491:16: Error: 'WidgetStateProperty' isn't a type.
      required WidgetStateProperty<Color?>? overlayColor}) {
               ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:590:12: Error: 'WidgetState' isn't a type.
      (Set<WidgetState> states) {
           ^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:589:29: Error: The getter 'WidgetStateProperty' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetStateProperty'.
    final defaultRowColor = WidgetStateProperty.resolveWith(
                            ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:591:29: Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetState'.
        if (states.contains(WidgetState.selected)) {
                            ^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:659:31: Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WidgetStatePropertyAll'.
                            ? WidgetStatePropertyAll(fixedColumnsColor)
                              ^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:665:31: Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WidgetStatePropertyAll'.
                            ? WidgetStatePropertyAll(fixedColumnsColor)
                              ^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:679:27: Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WidgetStatePropertyAll'.
                        ? WidgetStatePropertyAll(fixedColumnsColor)
                          ^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:728:31: Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WidgetStatePropertyAll'.
                            ? WidgetStatePropertyAll(fixedCornerColor)
                              ^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:737:31: Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WidgetStatePropertyAll'.
                            ? WidgetStatePropertyAll(fixedCornerColor)
                              ^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:743:31: Error: The method 'WidgetStatePropertyAll' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing method, or defining a method named 'WidgetStatePropertyAll'.
                            ? WidgetStatePropertyAll(fixedCornerColor)
                              ^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1038:42: Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetState'.
                              ?.resolve({WidgetState.hovered})
                                         ^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1041:60: Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetState'.
                      ? scrollBarTheme.thickness?.resolve({WidgetState.hovered})
                                                           ^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1067:52: Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetState'.
                                        ?.resolve({WidgetState.hovered})
                                                   ^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1071:48: Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetState'.
                                    ?.resolve({WidgetState.hovered})
                                               ^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1161:7: Error: 'WidgetStateProperty' isn't a type.
      WidgetStateProperty<Color?>? effectiveDataRowColor) {
      ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1329:7: Error: 'WidgetStateProperty' isn't a type.
      WidgetStateProperty<Color?>? effectiveDataRowColor,
      ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1333:7: Error: 'WidgetStateProperty' isn't a type.
      WidgetStateProperty<Color?> defaultRowColor,
      ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1350:21: Error: 'WidgetState' isn't a type.
          final Set<WidgetState> states = <WidgetState>{
                    ^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1350:44: Error: 'WidgetState' isn't a type.
          final Set<WidgetState> states = <WidgetState>{
                                           ^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1351:29: Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetState'.
            if (isSelected) WidgetState.selected,
                            ^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1352:29: Error: The getter 'WidgetState' isn't defined for the class 'DataTable2'.
 - 'DataTable2' is from 'package:data_table_2/src/data_table_2.dart' ('/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetState'.
            if (isDisabled) WidgetState.disabled,
                            ^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1399:7: Error: 'WidgetStateProperty' isn't a type.
      WidgetStateProperty<Color?>? effectiveHeadingRowColor, int numberOfCols) {
      ^^^^^^^^^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/data_table_2.dart:1416:51: Error: 'WidgetState' isn't a type.
        color: effectiveHeadingRowColor?.resolve(<WidgetState>{}),
                                                  ^^^^^^^^^^^
/C:/Users/user_name/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.15/lib/src/paginated_data_table_2.dart:350:9: Error: 'WidgetStateProperty' isn't a type.
  final WidgetStateProperty<Color?>? headingRowColor;
        ^^^^^^^^^^^^^^^^^^^

**Comment by maxim-saplin** [comment]
You need to upgrade Flutter via `flutter upgrade` - as of today 3.22.2 is the most recent version. In the above logs older Flutter is used.

Or you can downgrade the data_table_2 version in pub spec.yaml to 2.5.12
