### ISSUE TITLE
Checkboxes Not Showing

### ISSUE THREAD

**Issue by darkfrog26** [maxim-saplin/data_table_2#296]
I'm using `AsyncPaginatedDataTable2` and `showCheckboxColumn` is set to `true`, but no checkboxes appear. In earlier tests using static content the checkboxes were appearing fine. Is there something special I have to do to support this within `AsyncPaginatedDataTable2`?

**Comment by maxim-saplin** [comment]
If I remember it right, you need to set `onSelectChanged` handler

**Comment by darkfrog26** [comment]
Thanks @maxim-saplin, that seems to have done the trick. However, I can't seem to check the boxes.

**Comment by maxim-saplin** [comment]
You should take care of selected state, do proper handling of on select event and mark rows as selected

**Comment by darkfrog26** [comment]
I appreciate the support. I've got the checkboxes appearing, and I'm managing state, but the checkboxes are never checked. I've even tried making every `DataRow2.selected = true` and they are all unchecked.

**Comment by maxim-saplin** [comment]
Please check the examples, checkboxes are demonstrated there: https://github.com/maxim-saplin/data_table_2/tree/main/example
