### ISSUE TITLE
Zebra-striped Row

### ISSUE THREAD

**Issue by RizaldiWiratama** [maxim-saplin/data_table_2#30]
absolutely a great package for upgrading the DataTable features !

but i have an issue regarding zebra-striped row when i use DataTable2 (not occured in DataTable)

this is my code for zebra-striped row
```
DataRow2(
      color: MaterialStateProperty.resolveWith<Color>((Set<MaterialState> states) {
        if (i.isEven) //Change Color if Row is Even, this is for Stripped Table
          return Color.fromRGBO(235, 241, 244, 1);
        else
          return Colors.white;
      }),
      cells: [
          ...
      ],
    );
```

i try to use either DataRow or DataRow2 in DataTable2 but the result will be same like this
![image](https://user-images.githubusercontent.com/23089248/127803505-d1bb5dcd-b3a8-4e49-a4a5-d5f0939c32af.png)

but if i hover to some row in DataTable2, it will have the color of stripped row like this

![image](https://user-images.githubusercontent.com/23089248/127803844-efc86b90-b6ae-4d7d-a5e1-d2b7312313db.png)

can you check this issue? is it regarding to DataTable2 or not?  thank you so much

**Comment by maxim-saplin** [comment]
The stripes are doable with both Flutter DataTable and DataTable2, as you can see in this sample (using DataTable2): https://maxim-saplin.github.io/flutter_web_spa_sample/canvaskit/#/
I don't remember exatly the details, but it seems that with hovering enabled rows backgroud get's obstructed or smth like that. 
Could you please try the following code:
```
DataRow2(
              color: MaterialStateColor.resolveWith((states) =>
                  index % 2 == 1 ? Colors.grey[200]! : Colors.transparent),
```

**Comment by RizaldiWiratama** [comment]
hey i already try with your code, still same behavior like before

![image](https://user-images.githubusercontent.com/23089248/127832518-41cfa2a2-1c2d-4903-b038-8c3c9cbe4c58.png)

even when i add this code 
`selected: i.isEven ? true : false,` 
still same behavior

**Comment by maxim-saplin** [comment]
Will take a closer look latter and update you

**Comment by maxim-saplin** [comment]
Just check the code suggested above on examples, it works just fine:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/7947027/127919903-81623c59-15f2-4978-8dc9-e75170518703.png">

I'd recomend you checking what you have in data cells as it seems like you might have child widgets in cells having their own background which overlaps the color of rows

**Comment by RizaldiWiratama** [comment]
I found the problem , when i set "border" it will have that behavior, but if i comment this code the behavior dissapear
```
return DataTable2(
      border: TableBorder.all(color: Color.fromRGBO(226, 236, 233, 1)), // comment this, the behavior will dissapear
);
```
i want vertical border(divider) so i set this code 


i try this too , but same behavior
```
return DataTable2(
      border: TableBorder(
          top: BorderSide(color: Color.fromRGBO(226, 236, 233, 1)),
          bottom: BorderSide(color: Color.fromRGBO(226, 236, 233, 1)),
          left: BorderSide(color: Color.fromRGBO(226, 236, 233, 1)),
          right: BorderSide(color: Color.fromRGBO(226, 236, 233, 1)),
          verticalInside: BorderSide(color: Color.fromRGBO(226, 236, 233, 1)),
          horizontalInside: BorderSide(color: Color.fromRGBO(226, 236, 233, 1))),
);
```

any ideas or solution for this ?

**Comment by maxim-saplin** [comment]
Indeed there's a bug... Some research and ecventual change to the sources of the widget would be required to make it work.
In the meantime I can suggest you use Contrainer or ColoredBox inside cells and control row colors at this level.

**Comment by RizaldiWiratama** [comment]
okay thanks @maxim-saplin for the suggestion, i will try it

**Comment by RizaldiWiratama** [comment]
I use this code inside DataCell and success retaining vertical border with striped row table
```
return DataCell(
        Container(
          color: row.isEven ? Color.fromRGBO(235, 241, 244, 1) : Colors.white,
        ),
      );
```

![image](https://user-images.githubusercontent.com/23089248/127984166-9fc45d11-6f84-42cb-8008-71484752bea3.png)

thanks @maxim-saplin for the suggestion and help , i appreciate it most 👍

**Comment by maxim-saplin** [comment]
You are welcom)

**Comment by mubarakar** [comment]
I cannot use Container to apply color like that.. this was my result. Please suggest a work around
![Screenshot_1](https://user-images.githubusercontent.com/100112456/156931209-fcdcb171-3527-4b23-a7e0-8fa4108851c0.png)

**Comment by RizaldiWiratama** [comment]
@mubarakar share your minimal code in here , and what do you expect?

**Comment by mubarakar** [comment]
> I use this code inside DataCell and success retaining vertical border with striped row table
> 
> ```
> return DataCell(
>         Container(
>           color: row.isEven ? Color.fromRGBO(235, 241, 244, 1) : Colors.white,
>         ),
>       );
> ```
> 
> ![image](https://user-images.githubusercontent.com/23089248/127984166-9fc45d11-6f84-42cb-8008-71484752bea3.png)
> 
> thanks @maxim-saplin for the suggestion and help , i appreciate it most 👍

I am trying to do this, because of the issue that using table border disable the `DataRow()` color I am trying to use a `Container()` inside the `DataCell()`, but the container only wrapping the widget, that's why the cyan is only applied to the number. I need fill cyan full inside the DataCell as you did. There is padding or margin which is invisible for us. I tried using the height of the container to `double.infinity` and it fit the height but cannot do anything regarding the width.

![image](https://user-images.githubusercontent.com/100112456/157251764-74e9fbdf-0ef6-4084-8852-bb50bd8ba66a.png)

This is my code
```

                 DataCell(
                                Container(
                                  height: double.infinity,
                                  alignment: Alignment.center,
                                  color: Colors.cyan,
                                  child: Text(
                                    item.itemId.toString(),
                                  ),
                                ),
                              ),
```

**Comment by RizaldiWiratama** [comment]
oh i'm using color of DataRow for that case

```
DataRow.byIndex(
      index: index,
      color: isStrippedTable ? MaterialStateProperty.resolveWith<Color>((Set<MaterialState> states) {
        return index.isEven ? Color.fromRGBO(235, 241, 244, 1) : Colors.white;
      }) : null,
      cells: <DataCell>[
        ...
      ],
    );
```

**Comment by maxim-saplin** [comment]
Zebra stripes now work OK, in /example folder you can find how that works:

![image](https://user-images.githubusercontent.com/7947027/172548291-d0a08263-8422-47e7-a4f8-13826addd65d.png)
