### ISSUE TITLE
How to use different list in each DataTable column

### ISSUE THREAD

**Issue by DktPhl2019** [maxim-saplin/data_table_2#306]
Hello

This is not an issue, but rather a question. 

I asked the question here: https://stackoverflow.com/questions/79076159/how-to-use-different-list-in-each-datatable-column.

I am using Datatable2. 

The statement uses one list for both columns, in this example: rows: List<DataRow>.of(myList). 

My table has two columns: name and address

I need to find a way to use a different list in each column.

Do you have any ideas or suggestions?

If you reply on the stackoverflow, then you could close this issue. 

Thank you

**Comment by maxim-saplin** [comment]
Check SO, you don't get the point of data row containing data cells. Check tutorials.

**Comment by DktPhl2019** [comment]
Hello
Could you please be more specific. 
There is no tutorial that covers this topic. 
My issue is: 
The statement uses one list for both columns: rows: List<DataRow>.of(myList). 
I need to find a way to use a different list in each column. How do I do that?

If you don't know the answer then please say so. 
Thank you
    On Friday, October 11, 2024 at 05:08:24 PM EDT, Maxim Saplin ***@***.***> wrote:  
 
 


Check SO, you don't get the point of data row containing data cells. Check tutorials.

**Comment by maxim-saplin** [comment]
https://github.com/maxim-saplin/data_table_2/blob/main/example/lib/screens/data_table2_simple.dart - there's a list of row each containing a list of cells, each row contains exactly one cells per column
