### ISSUE TITLE
Is there a class to do a datatable search?

### ISSUE THREAD

**Issue by DktPhl2019** [maxim-saplin/data_table_2#311]
Hello

I need to do a table search. 

For example, my table has multiple columns. 

I need to find rows with a salary greater than 30000 and less than 50000.

Is there a way to do this using datatable2?

Thank you

**Comment by Vladeouz** [comment]
Any progress for this ?

**Comment by maxim-saplin** [comment]
There's no plan to include this feature as a part of package. data_table_2 was never intended to be a rich grid control, hence the assumption is that one can create own grid by adding additional widgets (e.g. filter) and managing the state.

Here's an example:
https://maxim-saplin.github.io/flutter_web_spa_sample/canvaskit/#/
https://github.com/maxim-saplin/flutter_web_spa_sample

**Comment by DktPhl2019** [comment]
Hello
There are no issues now. You've already closed the ticket. 
Thank You
Dmitri Kozlov    On Thursday, November 21, 2024 at 02:12:24 AM EST, Maxim Saplin ***@***.***> wrote:  
 
 


Reopened #311.
