### ISSUE TITLE
I cannot initially go to the last page of the PaginatedDataTable2

### ISSUE THREAD

**Issue by Josua2012** [maxim-saplin/data_table_2#32]
Hi Maxim,

To initially place myself on the last page of the `PaginatedDataTable2 `widget I have used this code:
```
 @override
  Widget build(BuildContext context) {  
    final logProvider = Provider.of<LogProvider>(context, listen: true);
    if (logProvider.lastPage) {
      logProvider.lastPage = false;
      Future(() {
        _controller!.goToLastPage();  // <<<<<<<<<<<<<<<<<<<
      });
    }

    return PaginatedDataTable2(
     ....
```

But it returns the following error:

`RangeError (index): Index out of range: index must not be negative: -11`

Could you tell me how I can initially place myself on the last page?

Thank you very much for the help. 

Regards,
Jose

**Comment by maxim-saplin** [comment]
Could you please provide stack trace?

**Comment by Josua2012** [comment]
════════ Exception caught by widgets library ═══════════════════════════════════
The following IndexError was thrown building LayoutBuilder:
RangeError (index): Index out of range: index must not be negative: -11

```
The relevant error-causing widget was
PaginatedDataTable2
lib\…\views\log_view.dart:296
When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 581:7             _get]
packages/electro_app/ui/views/powercontrol_view.dart 44:27                                                                 getRow
packages/data_table_2/paginated_data_table_2.dart 492:60                                                                   <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/identity_hash_map.dart 75:23    putIfAbsent
...

```

**Comment by Josua2012** [comment]
Perhaps it would be interesting that if the initialFirstRowIndex property is < 0 it is automatically placed on the last page?

**Comment by Josua2012** [comment]
Note that the autoRowsToHeight property is true.

**Comment by maxim-saplin** [comment]
Do you pass in a negative initialFirstRowIndex?

**Comment by Josua2012** [comment]
No.
initialFirstRowIndex: 0,

**Comment by maxim-saplin** [comment]
I'd suggest you setting breakpoint in paginated_data_table2.dart at the line where the exception occurs and tracing from there. Might be related to the data source, don't have ideas, what's wrong

**Comment by Josua2012** [comment]
The exception occurs in:
`child: PaginatedDataTable2(`
in my own file log_view.dart
```
        Expanded(
            child: Listener(
              onPointerSignal: (pointerSignal) {
                if (pointerSignal is PointerScrollEvent) {
                  // do something when scrolled
                  //PointerScrollEvent pp = pointerSignal as PointerScrollEvent;

                  //print('Scrolled ${pp.scrollDelta.dy}');

                  if (pointerSignal.scrollDelta.dy > 0) {
                    _controller!.goToNextPage();
                  }
                  if (pointerSignal.scrollDelta.dy < 0) {
                    _controller!.goToPreviousPage();
                  }
                }
              },
              child: PaginatedDataTable2(
                autoRowsToHeight: true,
                columnSpacing: 5,
                wrapInCard: true,
                initialFirstRowIndex: 0, 
                controller: _controller,
```

Have you tried it in any of your examples?

**Comment by Josua2012** [comment]
Okay. I am going to do tests

**Comment by Josua2012** [comment]
Maxim,
I have found the problem.
First I have done tests with your examples and I have verified that your example of PaginatedDataTable2 with the modifications to place itself on the last page worked correctly.
Later I have delved into my code and the problem is that in your example the data is loaded directly, the datasource already contains the data to be displayed, however, in my code, the data is loaded from a server and therefore the data load it is done through asynchronous calls, which is more complex (Dio library).
I have been able to solve it by including some flags so that if the asynchronous load has not finished the rendering of the table is not done nor the call to goToLastPage.
In my code, after the load, a notifyListeners (through provider) was executed so that It will refresh the content of the table, now we have to stop the rendering with the flags that I have set and wait until the data load has finished before doing anything with the PaginatedDataTable2. 
Regards,
Jose

**Comment by Josua2012** [comment]
Maxim,
However, perhaps it would be interesting to do some mechanism by which, initially, the table could be placed directly on the last page, since it produces a somewhat strange effect, first the first page is shown and immediately it is refreshed to show the last page. 
What do you think?

**Comment by maxim-saplin** [comment]
I think that is doable with the current implementation. On the first build, when you pass controller and and it is being attached to the table, have the data source empty. Then init second build via data source, this time with data and have the controller scroll to last page. I wouldn't put that corner case as a piece of widget features

**Comment by Josua2012** [comment]
Theoretically, what you propose is correct. 
However, I have done several tests and I do not know how to make it go correctly, the error that I told you yesterday is momentarily displayed:
```
The following IndexError was thrown building LayoutBuilder:
RangeError (index): Index out of range: index must not be negative: -11
```
although afterwards the last page is shown.

I don't know exactly where put the code to load the rows so that that error doesn't occur. :(
Check out the following video: https://recordit.co/au65Cznlkl

Regards,
Jose

**Comment by maxim-saplin** [comment]
It is really hard to troubleshoot the code not related to the widget in this repo) Clearly you have done much staff in the client code and from your examples it is hard to see isolated issues related to the widget, as well as straightforward repro steps that show unexpected behavior in the widget itself

**Comment by Josua2012** [comment]
When you finish the development of async I will do new tests and if it still does not work I will make you a complete example so you can see the problems. 
Thanks.

**Comment by Josua2012** [comment]
I have also been able to verify that if there are **no rows in the datasource**, executing `goToLastPage` produces the error that I mentioned earlier. 
Code:
```
  @override
  Widget build(BuildContext context) {
      Future(() {
        _controller!.goToLastPage();
      });
......
```
Error:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following IndexError was thrown building LayoutBuilder:
RangeError (index): Index out of range: index must not be negative: -11

The relevant error-causing widget was
PaginatedDataTable2
lib\…\views\log_view.dart:306
When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 581:7             _get]
packages/electro_app/datatables/log_datasource.dart 141:25                                                                 getRow
packages/data_table_2/paginated_data_table_2.dart 492:60                                                                   <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/identity_hash_map.dart 75:23    putIfAbsent
...
```

**Comment by maxim-saplin** [comment]
@Josua2012 I've published a new version to pub.dev - there's a new feature added specifically to align current page number and page size with the total number of records returned by data source: `PageSyncApproach` enum and `pageSyncApproach` constructor param for async table. This feature might help you with the 2 issues your brought up previulsy:
1. Starting with last page with auto rows. Set page sync to PageSyncApproach.goToLast, set inital row to sum large number (say a million) - the widget will make first request, get 0 rows and actual row count and right away send a second request to with calculated last page row index
2. Keeping table at the last page after data source refreshes should the data source return fewer rows

**Comment by Josua2012** [comment]
Hi @maxim-saplin 
Now it works wonderfully well. It’s great. 
Thank you very much for all your work. 
Regards,
Jose.
