### ISSUE TITLE
Add headingRowAlignment property to DataColumn2

### ISSUE THREAD

**Issue by brynn** [maxim-saplin/data_table_2#320]
This is a property on `DataColumn`: https://api.flutter.dev/flutter/material/DataColumn/headingRowAlignment.html

But it is not currently exposed by `DataColumn2`: https://github.com/maxim-saplin/data_table_2/blob/main/lib/src/data_table_2.dart#L28-L34

**Comment by maxim-saplin** [comment]
Fixed in 2.5.18
