### ISSUE TITLE
PaginatedDataTable2: save double(scroll position?), instead of int for _firstRowIndex 

### ISSUE THREAD

**Issue by Alexqwesa** [maxim-saplin/data_table_2#323]
PaginatedDataTable2: on init read PageStorage and expected type int, but got double

Steps to reproduce:
1) change page in PaginatedDataTable2 ,
2) scroll few records on  PaginatedDataTable2
3) go to other screen and back

Code from 'paginated_data_table_2.dart':

```dart 
  @override
  void initState() {
    super.initState();
    _firstRowIndex = PageStorage.of(context).readState(context) as int? ??  // here i got error
        widget.initialFirstRowIndex ??
        0;
    widget.source.addListener(_handleDataSourceChanged);
    _effectiveRowsPerPage = widget.rowsPerPage;
    widget.controller?._attach(this);
    _handleDataSourceChanged();
  }
```

**Comment by maxim-saplin** [comment]
?

**Comment by maxim-saplin** [comment]
I don't see any valid/sufficient description: steps, screenshots, etc. - whatever might be necessary to diagnose it

**Comment by Alexqwesa** [comment]
Expected :
PaginatedDataTable2  should store/load _firstRowIndex in PageStorage

Actual:
It throw error: type 'double' is not a subtype of type 'int?' in type cast  
(at line i showed in first post),

here is also steps (i added them to first comment...)

Steps to reproduce:

1) change page in PaginatedDataTable2 ,
2) scroll few records on PaginatedDataTable2
3) go to other screen and back

**Comment by maxim-saplin** [comment]
You might try PaginatdDataTable2 from the /examples to see if the issue can be reproduced there

**Comment by maxim-saplin** [comment]
https://maxim-saplin.github.io/data_table_2/#/datatable2

**Comment by Alexqwesa** [comment]
Steps to reproduce:
0) wrap page with PageStorage widget (with global bucket....)
0.5) PaginatedDataTable2 (key: const PageStorageKey("storage_anykey"), .....
1) change page in PaginatedDataTable2 ,
2) scroll few records on PaginatedDataTable2
3) go to other screen and back - error

**Comment by maxim-saplin** [comment]
I can look into the issue you if you provide a reproducible code snippet, if you fork the repo, make the changes and share the link to where you've made the changes - that would be helpful
