### ISSUE TITLE
The superclass, 'DataColumn', has no unnamed constructor that takes no arguments.

### ISSUE THREAD

**Issue by 7Karol7Pay** [maxim-saplin/data_table_2#325]
I am trying to run my project, but I am getting the following errors:

````
../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:28:9: Error: The superclass, 'DataColumn', has no unnamed constructor that takes no arguments.
  const DataColumn2(
        ^^^^^^^^^^^
../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:525:47: Error: The method 'withValues' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
              ? effectiveDataTextStyle.color!.withValues(alpha: 0.6)
                                              ^^^^^^^^^^
../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:596:44: Error: The method 'withValues' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
          return theme.colorScheme.primary.withValues(alpha: 0.08);
                                           ^^^^^^^^^^
../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:647:13: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('../../../../../../fvm/versions/3.22.2/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
            defaultRowColor,
            ^
../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:674:25: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('../../../../../../fvm/versions/3.22.2/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                        defaultRowColor,
                        ^
../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:688:21: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('../../../../../../fvm/versions/3.22.2/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                    defaultRowColor,
                    ^
../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:716:21: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('../../../../../../fvm/versions/3.22.2/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                    defaultRowColor,
                    ^
../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:752:25: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('../../../../../../fvm/versions/3.22.2/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                        defaultRowColor,
                        ^
../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:844:45: Error: The getter 'headingRowAlignment' isn't defined for the class 'DataColumn'.
 - 'DataColumn' is from 'package:flutter/src/material/data_table.dart' ('../../../../../../fvm/versions/3.22.2/packages/flutter/lib/src/material/data_table.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headingRowAlignment'.
                headingRowAlignment: column.headingRowAlignment ??
                                            ^^^^^^^^^^^^^^^^^^^
../../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:845:36: Error: The getter 'headingRowAlignment' isn't defined for the class 'DataTableThemeData'.
 - 'DataTableThemeData' is from 'package:flutter/src/material/data_table_theme.dart' ('../../../../../../fvm/versions/3.22.2/packages/flutter/lib/src/material/data_table_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headingRowAlignment'.
                    dataTableTheme.headingRowAlignment ??
                                   ^^^^^^^^^^^^^^^^^^^
````

I am using version: 2.5.15. I tried changing to version 2.5.18, but the error persists.

**Comment by maxim-saplin** [comment]
You might want to upgrade Flutter (flutter upgrade) or revert to version 2.5.16

**Comment by 7Karol7Pay** [comment]
> You might want to upgrade Flutter (flutter upgrade) or revert to version 2.5.16

I changed the version to 2.5.16, but it didn't work. Unfortunately, I can't change the Flutter version. Is there a way to fix this issue without changing the Flutter version?

**Comment by maxim-saplin** [comment]
Double check which version you actually have, headingRowAlignment references are missing in 2.5.16

**Comment by SheharyarAmin** [comment]
I'm having the same error message

Here's my flutter version:

flutter --version
Flutter 3.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5dcb86f68f (9 months ago) • 2024-05-09 07:39:20 -0500
Engine • revision f6344b75dc
Tools • Dart 3.4.0 • DevTools 2.34.3

Error Message:
/C:/Users/Advocate%20Hamza%20Gujja/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:28:9: Error: The superclass, 'DataColumn', has no unnamed constructor that takes no arguments.
  const DataColumn2(
        ^^^^^^^^^^^
/C:/Users/Advocate%20Hamza%20Gujja/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:525:47: Error: The method 'withValues' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
              ? effectiveDataTextStyle.color!.withValues(alpha: 0.6)
                                              ^^^^^^^^^^
/C:/Users/Advocate%20Hamza%20Gujja/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:596:44: Error: The method 'withValues' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
          return theme.colorScheme.primary.withValues(alpha: 0.08);
                                           ^^^^^^^^^^
/C:/Users/Advocate%20Hamza%20Gujja/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:647:13: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('/D:/FlutterSDK/flutter/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
            defaultRowColor,
            ^
/C:/Users/Advocate%20Hamza%20Gujja/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:674:25: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('/D:/FlutterSDK/flutter/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                        defaultRowColor,
                        ^
/C:/Users/Advocate%20Hamza%20Gujja/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:688:21: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('/D:/FlutterSDK/flutter/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                    defaultRowColor,
                    ^
/C:/Users/Advocate%20Hamza%20Gujja/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:716:21: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('/D:/FlutterSDK/flutter/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                    defaultRowColor,
                    ^
/C:/Users/Advocate%20Hamza%20Gujja/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:752:25: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('/D:/FlutterSDK/flutter/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                        defaultRowColor,
                        ^
/C:/Users/Advocate%20Hamza%20Gujja/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:844:45: Error: The getter 'headingRowAlignment' isn't defined for the class 'DataColumn'.
 - 'DataColumn' is from 'package:flutter/src/material/data_table.dart' ('/D:/FlutterSDK/flutter/packages/flutter/lib/src/material/data_table.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headingRowAlignment'.
                headingRowAlignment: column.headingRowAlignment ??
                                            ^^^^^^^^^^^^^^^^^^^
/C:/Users/Advocate%20Hamza%20Gujja/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:845:36: Error: The getter 'headingRowAlignment' isn't defined for the class 'DataTableThemeData'.
 - 'DataTableThemeData' is from 'package:flutter/src/material/data_table_theme.dart' ('/D:/FlutterSDK/flutter/packages/flutter/lib/src/material/data_table_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headingRowAlignment'.
                    dataTableTheme.headingRowAlignment ??
                                   ^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.
