### ISSUE TITLE
Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.

### ISSUE THREAD

**Issue by bahiraei** [maxim-saplin/data_table_2#326]
/C:/Users/FR1/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:525:47: Error: The method 'withValues' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
              ? effectiveDataTextStyle.color!.withValues(alpha: 0.6)
                                              ^^^^^^^^^^
/C:/Users/FR1/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:596:44: Error: The method 'withValues' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
          return theme.colorScheme.primary.withValues(alpha: 0.08);
                                           ^^^^^^^^^^
/C:/Users/FR1/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:647:13: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('/E:/SDK/flutter/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
            defaultRowColor,
            ^
/C:/Users/FR1/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:674:25: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('/E:/SDK/flutter/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                        defaultRowColor,
                        ^
/C:/Users/FR1/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:688:21: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('/E:/SDK/flutter/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                    defaultRowColor,
                    ^
/C:/Users/FR1/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:716:21: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('/E:/SDK/flutter/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                    defaultRowColor,
                    ^
/C:/Users/FR1/AppData/Local/Pub/Cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:752:25: Error: The argument type 'WidgetStateProperty<dynamic>' can't be assigned to the parameter type 'WidgetStateProperty<Color?>'.
 - 'WidgetStateProperty' is from 'package:flutter/src/widgets/widget_state.dart' ('/E:/SDK/flutter/packages/flutter/lib/src/widgets/widget_state.dart').
 - 'Color' is from 'dart:ui'.
                        defaultRowColor,
                        ^
Target kernel_snapshot_program failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'E:\SDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
Running Gradle task 'assembleRelease'...                           54.3s

**Comment by maxim-saplin** [comment]
Revert to data_table_2 2.5.15 or run `flutter upgrade`
