### ISSUE TITLE
Color' is from 'dart:ui

### ISSUE THREAD

**Issue by hina06botify** [maxim-saplin/data_table_2#329]
../../../.pub-cache/hosted/pub.dev/data_table_2-2.5.18/lib/src/data_table_2.dart:596:44: Error: The method 'withValues' isn't defined for the class 'Color'.
 - 'Color' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
          return theme.colorScheme.primary.withValues(alpha: 0.08);

**Comment by maxim-saplin** [comment]
Run `flutter upgrade` or revert to data_table_2 `2.5.16`

**Comment by hina06botify** [comment]
i'm already try it and my flutter version is 3.24.3

**Comment by hina06botify** [comment]
i'm already try it and my flutter version is 3.24.3

**Comment by maxim-saplin** [comment]
The most recent stable version is 3.27.0
