### ISSUE TITLE
When a refresh is made, the page remains on the current page even if that page does not contain rows

### ISSUE THREAD

**Issue by Josua2012** [maxim-saplin/data_table_2#33]
Maxim,
I have observed a problem.
Imagine, we have a PaginatedDataTable2 that contains 200 rows distributed over several pages, now I am on the last page (page 20 / rowsPerpage: 10).
Now imagine that we have put in the window a button to "refresh" the rows from the server. 
In the case that all but 1 lines have been deleted, if the "refresh" button is clicked, the PaginatedDataTable2 widget will remain on the last page, when actually the table now only has one page containing one row. A normal grid of a windows desktop application, when doing the refresh, would show the only record that remains. The PaginatedDataTable IMHO should also show the first page that contains the only table row left after rows deletion.
What do you think? 
Thanks.
Regards,
Jose

**Comment by maxim-saplin** [comment]
Indeed, need to look into that case. Will do after the async stuff

**Comment by Josua2012** [comment]
Perfect. It is something quite important, it gives users the feeling that the application does not work well. 
Thanks Maxim.

**Comment by maxim-saplin** [comment]
JIC, this is standard behaviour of Flutter paginated table, showing empty rows - and it in fact makes sense, the ideas is such that rows can be loaded indivdually and data source can have return not exact row count. Though I agree it makes sense to look into the issue and see if a better approach can be introduced without affecting standard behaviour

**Comment by Josua2012** [comment]
In that case, the isRowCountApproximate property will surely have to be taken into account so that it behaves in one way or another. :)
Thanks.

**Comment by maxim-saplin** [comment]
This should be fixed with AsycnPaginatedDataTable2, the old one is not changed
