### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Galaxarum** [maxim-saplin/data_table_2#36]
Is there a way to display a custom footer on the side of the page number?

**Comment by maxim-saplin** [comment]
1. You can use `Stack` and put some widget on top of the `PaginatedDataTable2`
2. You can disable the footer, use `PaginatorController` and custom widget (which can be placed to `Column` below the table) to draw your own footer

There's an example of customer pager boing displayed on top of table via `Stack`: https://maxim-saplin.github.io/data_table_2/#/paginated2 (right top corner -> Custom pager)
