### ISSUE TITLE
Dynamic DataRow2 Height setting

### ISSUE THREAD

**Issue by zzzaJ** [maxim-saplin/data_table_2#37]
Hi there,

I have run into this issue several times. I cannot figure out how to set the height of each data row to fully wrap the text contained within it.

It often just cuts off some of the text that is displayed in the row when it is too long to fit on a single line.

Am I missing a param for this? Or is it not supported at the moment?

**Comment by maxim-saplin** [comment]
Hi. All rows are fixed width and there's no logic in the Widgets that can help to size their rows, columns and cells to fit contents. The only advice I can give is choosing widths (columns adapt to parent width OR `minWitdh`) and heights that work for most of the anticipated cases.
