### ISSUE TITLE
Total row

### ISSUE THREAD

**Issue by aturiel** [maxim-saplin/data_table_2#38]
Is there a way to display a total row on DataTable2?

This row should not be involved in any kind of sorting.

Thanks

**Comment by maxim-saplin** [comment]
1. Is there a feature that will build a summary row for you (e.g. calculate aggregates, outline summaries etc.) - No
2. Is there a placeholder property or special kind of data row that displays summary row - No
3. How can a summary row be created - DataTable2 is indifferent to data rows it is asked to display. Developer is free to use any of the rows as summary when generating the list of data rows (directly or via data source). E.g. one can prepare the list of N rows with N-1 rows containing data and N-th rows having calculated agregates (and e.g. some special formating)
4. Is it possible to fix/make sticky any data row (e.g. the last one) - No

**Comment by aturiel** [comment]
Thanks Maxin, I think I will go for option 3.  

Thanks and by they way a very useful package you have 😉

**Comment by maxim-saplin** [comment]
:)

**Comment by aturiel** [comment]
Already done, was easier than expected.

![Screenshot 2021-08-20 at 17 01 56](https://user-images.githubusercontent.com/27290047/130253454-0f92bfd8-4e15-498d-ab8a-1464d1adf322.png)

**Comment by maxim-saplin** [comment]
Looking good  👍
