### ISSUE TITLE
datatable scrollcontroller

### ISSUE THREAD

**Issue by selvam920** [maxim-saplin/data_table_2#4]
i want to attach scrollController in rows, 
how to do that

**Comment by maxim-saplin** [comment]
Will look into that, shouldn't be a problem

**Comment by maxim-saplin** [comment]
I've just pubblished 2.0.3m there's scroll controller exposes in both tables. You can check a new example here: https://github.com/maxim-saplin/data_table_2/blob/main/example/lib/data_table2_scrollup.dart

**Comment by selvam920** [comment]
Thanks..
