### ISSUE TITLE
PaginatedDataTable2 is not working under child of SingleChildScrollView

### ISSUE THREAD

**Issue by santhoshrao519** [maxim-saplin/data_table_2#41]
Firstly thanks for the amazing PaginatedDataTable. When im using it with SingleChildScrollView, it is not rendering on screen. Please check

**Comment by santhoshrao519** [comment]
I have about 15 DataColumns in a table, so for that i need to apply horizontal scroll for datacolumns. How could I achieve this?

**Comment by maxim-saplin** [comment]
You can set minWidth (e.g. to 1200) and whenever the  container is narrowest table will be clipped and horizontal scroll will be active

**Comment by santhoshrao519** [comment]
Thanks, will follow it
