### ISSUE TITLE
Feature : Merge Columns

### ISSUE THREAD

**Issue by RizaldiWiratama** [maxim-saplin/data_table_2#43]
is it possible to merge columns like this mockup ? if no, will this be a new feature in this package?
![image](https://user-images.githubusercontent.com/23089248/131287608-0257c097-9f98-4039-a2e9-614ac34558ce.png)
so the first row will be merged into 1 column and 2nd row still containing 3 columns

i need your suggestion/solution for this case @maxim-saplin thanks

**Comment by maxim-saplin** [comment]
There's no such feature. Besides the current design of the widget doesn't allow for solid row/col spanning without a total overhaul of code - that's smth unlikely to happen. I would advice you looking at the direction of fully featured Grid controls.

The screen you shows can be replicated with the current control though. You can use 2 `Row`s and 3 `Column`s (in the bottom row) and put there `Container`s to recreate cells in the header. Data cell in the `DataRow` can have a `Row` with 3 `Container`s to display U, P, O values. Border can be recreated via `Container`s  borders.

**Comment by RizaldiWiratama** [comment]
thanks @maxim-saplin for suggestion will try it later

**Comment by anggaaryas** [comment]
hi @maxim-saplin , can we sync 2 table horizontal scroll? for example header  , and data table?

**Comment by maxim-saplin** [comment]
Not sure I understood the question. Yet if you ask if scroll positions within the widgets can be controlled externally, you can do that by using scrollController property, though it only controls vertical direction, no such controller exposed to vertical scrolling

**Comment by anggaaryas** [comment]
like this:


```
|                          |      NameB       |
|        nameA             |------------------|
|                          |  A    |   B  | C |


|   someText               |   0   |   0  | 0 |
|   someText               |   0   |   0  | 0 |
|   someText               |   0   |   0  | 0 |
...
```

i create 2 table. one is for header table with 2 row and 1 column (merged cell using container), and one is for data table with 4 rows. when i scroll the header horizontally. can data table follow header table position?

**Comment by maxim-saplin** [comment]
No ideas except going into sources of the widget and making changes there (i.e. exposing a new controller)

**Comment by anggaaryas** [comment]
But, it has good solution right? Maybe i research about this feature 🤔

Pada tanggal Kam, 19 Jan 2023 16.48, Maxim Saplin ***@***.***>
menulis:
