### ISSUE TITLE
New feature of debouncing. 

### ISSUE THREAD

**Issue by jamolina2021** [maxim-saplin/data_table_2#45]
Hi Maxim,

Could it be that with the debouncing the navigation between pages goes a little slower than before? 
Or is it just a feeling of mine? 

Thanks.

**Comment by maxim-saplin** [comment]
Hi @jamolina2021 , I haven't added any debouncing to the widgets. In the examples deboncung is only used in async example. Not sure if there's any issues until you provide any detail

**Comment by maxim-saplin** [comment]
Though I night be wrong. In async table in `_fetchData` there's indeed a 700ms debouncing. Though it shouldn't create any delays. Let me know if you have any troubles with that

**Comment by Josua2012** [comment]
No problems. Thanks @maxim-saplin.
