### ISSUE TITLE
add an option to disable rendertime log print

### ISSUE THREAD

**Issue by insinfo** [maxim-saplin/data_table_2#46]
add an option to disable rendertime log print

**Comment by maxim-saplin** [comment]
OK)

**Comment by maxim-saplin** [comment]
In the newer version rendering time is only displayed in Debug configuration

**Comment by insinfo** [comment]
@maxim-saplin
the ideal is to disable this log because it makes it difficult to see the log messages of the application that the developer is working on

**Comment by maxim-saplin** [comment]
Use Profile or Release mode, filter out DataTable2 logs or fork and disable the prints in packages sources - no programatic way to do that in Debug mode

**Comment by gslender** [comment]
> DataTable2 logs or fork and disable the prints in packages sources - no programatic way to do that in Debug mode

Not entirely true - super easy to add a programatic (debugLogsOn:false) in the DataTable2 constructor and in the package have a line similar to `if (debugLogsOn) debugPrint(' etc` whereever you're using debugPrint etc.

Is it really ideal to require users to fork the package as the solution to a reasonable request to not have the package spew debug logs to the console when it is assumed the package is working fine? The logs serve zero purpose to anyone using the package right ??

I use around 60 packages and this is the only library that does this - so seems an odd approach to take !?
