### ISSUE TITLE
Allow setting column's absolute width 

### ISSUE THREAD

**Issue by coldwaterfish** [maxim-saplin/data_table_2#47]
how can I set sigle Cell's width

**Comment by carmas123** [comment]
I've created a pull request to do that.
Enjoy :)

https://github.com/maxim-saplin/data_table_2/pull/49

**Comment by coldwaterfish** [comment]
> I've created a pull request to do that. Enjoy :)
> 
> #49

ok

**Comment by maxim-saplin** [comment]
Added `DataCoulm2.fixedWidth` and pushed to pub.dev
