### ISSUE TITLE
DataTable global theme data

### ISSUE THREAD

**Issue by hazem-saeed** [maxim-saplin/data_table_2#48]
I tried to change the look of the table from the theme data (globally), so it would look the same throughout the entire app.
I succeeded to some extent, but styling the TableBorder from the theme data wasn't possible.

Is there a way that I don't know of to style the TableBorder from the theme data?

Thanks in advance...

**Comment by maxim-saplin** [comment]
JIC, I one approached the question of using custom theme fields, might be usefeul to your tasks: https://stackoverflow.com/questions/49172746/is-it-possible-extend-themedata-in-flutter/65421192#65421192
