### ISSUE TITLE
Table is not scrollable inside a column

### ISSUE THREAD

**Issue by Simouche** [maxim-saplin/data_table_2#5]
I want to display a column, with a search input and data table below it.
but when I do that, the data table looses the scrollability.

example:
`Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        FormTextField(labelText: translate(Keys.Global_Search)),
        Card(child: ProductsTable()),
      ],
    );`
  
when i use `ProductsTable` alone (without column nor TextField) it works properly.
but i need to add the search field.
any ideas?

**Comment by maxim-saplin** [comment]
Away from laptop to try a fix... Try wrapping ProductTable (assuming it has DataTable2 inside) in Flexible widget and play with fit property

**Comment by Simouche** [comment]
sorry for the late feedback, just wrapping it inside a flexible, made it work like before.
thank you

**Comment by maxim-saplin** [comment]
Great!
