### ISSUE TITLE
How can we export data tables to pdf/excel/other formats? 

### ISSUE THREAD

**Issue by MalikSamiAwan** [maxim-saplin/data_table_2#54]
Does data table supports printing option? or we have to use our own logic for that. And thankyou for the nice package

**Comment by maxim-saplin** [comment]
Frankly speaking, I have no idea how any Flutter widget can be exported to PDF. Would be nice to hear if there's a general approach to that.
Talking of the widget, there're no any features aiming exports. I would imagine a solution where there's some data as plain objects and there're different rendering pipelines through which the data can be put through:
- For on screen display - Flutter pipeline with widgets
- PDF - some plug-in yielding a binary stream 
- etc.

In other word is would be necessary to work on coding separate preesentation layers, be it file of certain format or on screen display.

**Comment by MalikSamiAwan** [comment]
Thankyou sir
