### ISSUE TITLE
Navigation improvements in the PaginatedDataTable2 and AsyncPaginatedDataTable2 (Auto Rows mode) 

### ISSUE THREAD

**Issue by Josua2012** [maxim-saplin/data_table_2#55]
Hi Maxim,
When you have time you could consider the following idea:
In the PaginatedDataTable2 widget and in the AsyncPaginatedDataTable2 widget (auto rows mode), with the mouse wheel or with a finger touch moving up or down the user could move up or down the rows as it is done in the DataTable2, in this way the user would have the best of both worlds, navigation between rows and navigation between pages.
![2021-11-06_11-41-29](https://user-images.githubusercontent.com/1523607/140607109-aae287a0-7b45-4167-b884-f763ca78cd32.jpg)
Thank you very much for all your work. 
Regards,
Jose

**Comment by maxim-saplin** [comment]
Hi Josua, not sure I'll have time for that feature any time soon. IMHO, the feature you require can be recreaed via a custom geature detector wrapping a widget and using paginator controller. If you happen to do that capability, I'll be happy to add it as a separate example (say to AsyncPaginatedDataTable2)

**Comment by Josua2012** [comment]
Ok. Thanks @maxim-saplin.
