### ISSUE TITLE
Server side pagination, query parameters are possible?

### ISSUE THREAD

**Issue by mohamedridzwan786** [maxim-saplin/data_table_2#58]
We are looking into do server side pagination and also query parameters, is this possible in paginated datatable 2 in future updates?

**Comment by maxim-saplin** [comment]
https://pub.dev/documentation/data_table_2/latest/data_table_2/AsyncPaginatedDataTable2-class.html  - AsyncPaginatedDataTable2 is already available and created for such cases. You might want to cline the repo and check the examples
