### ISSUE TITLE
Editing cell values.

### ISSUE THREAD

**Issue by Govindbetterlives** [maxim-saplin/data_table_2#61]
Allows users to edit cell values.

**Comment by maxim-saplin** [comment]
If you put widgets accepting user input into cells they will work just fine. E.g.

```
DataCell(
    TextFormField(
     initialValue: '$value', 
     keyboardType: textType, 
     onFieldSubmitted: (val){
        print('onSubmited $val');
     },
   ))
```

**Comment by Govindbetterlives** [comment]
Hi, i need this type of style. can you suggest me how can i implement this.

https://codepen.io/eirenaios/pen/VbZagL

**Comment by maxim-saplin** [comment]
I'd approach that kind of task with state full widgets OR some state management techniques, e.g. using Provider package - have all cells on a single row contain widgets that become editable when edit button is clicked.

Will leave the issue open to have an example added some time in the future
