### ISSUE TITLE
Need accordion view in Mobile resolution 

### ISSUE THREAD

**Issue by Govindbetterlives** [maxim-saplin/data_table_2#63]
Hi, Need accordion view in Mobile resolution .
 Ex.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/81243940/148492927-97269926-9134-4547-b5d7-05e58d1393e5.png)

**Comment by maxim-saplin** [comment]
Not a trivial feature that might require significant code rewrite, keeping the issue open for further evaluation
