### ISSUE TITLE
Do not display empty rows in PaginbatedDataTable2 (when the current page size is larger than the number of rows available)

### ISSUE THREAD

**Issue by astheras** [maxim-saplin/data_table_2#66]
[screenshot](https://ibb.co/T4wjznd)

**Comment by maxim-saplin** [comment]
There's no such capability at the moment. This is by design behavior

**Comment by maxim-saplin** [comment]
Keeping it open, might consider it for future implementation

**Comment by maxim-saplin** [comment]
Indeed, `PaginatedDataTable2. renderEmptyRowsInTheEnd.html ` has been implemented quite a while go: 
https://pub.dev/documentation/data_table_2/latest/data_table_2/PaginatedDataTable2/renderEmptyRowsInTheEnd.html
