### ISSUE TITLE
refreshDatasource() does not update total rows length on deleting row

### ISSUE THREAD

**Issue by MalikSamiAwan** [maxim-saplin/data_table_2#67]
When i delete row from the table and call the refreshDatasource() it does not update the total length of table.

**Comment by maxim-saplin** [comment]
How do you delete row?

**Comment by maxim-saplin** [comment]
Was not able to reproduce the issue on my end, examples have refreshDataSource with filter changing ingredients the number of rows displayed.

Feel free to reopen the issue providing steps to reproduce and code snippets
