### ISSUE TITLE
Rows Per Page Problem in AsyncPaginatedDataTable2

### ISSUE THREAD

**Issue by MalikSamiAwan** [maxim-saplin/data_table_2#69]
In AsyncPaginatedDataTable2 if i rowsPerPage:50 and availableRowsPerPage [50,100,250] it does not work. It only shows 50 in dropdown 
Hope you got my point

Thanks for helping

**Comment by maxim-saplin** [comment]
Hello. I'd assume that the number of rows is less than 100 - the widget cuts off all `availableRowsPerPage` which are lower than actual number of rows

![image](https://user-images.githubusercontent.com/7947027/157381096-2bf14e08-c143-4bd9-badc-8f6006064b09.png)
