### ISSUE TITLE
Feature - heading row decoration for gradients - or custom styles

### ISSUE THREAD

**Issue by ervindobri** [maxim-saplin/data_table_2#72]
Header should have decoration so maybe a gradient background can be set...
headingRowColor should be deprecated in favor of headingRowDecoration.

For example:

```
headingRowDecoration: BoxDecoration(
          gradient: LinearGradient(...),
        ),
```

**Comment by maxim-saplin** [comment]
Thanks for the suggestion. Will keep open and investigate when I have time

**Comment by Swado** [comment]
- Interested in contributing, @maxim-saplin.
- Proposing to maintain headerRowColor.
- Introducing a new headerRowDecoration field.
- This field will override the current BoxDecoration.
- It takes precedence over headerRowColor when both are provided.

**Comment by maxim-saplin** [comment]
Hi @Swado , thanks. How do you see thay new feature workinf in case there're more than 2 fixed rows, or if there're also a fixed column? There're colors for fixed sections (rows, colors and their intersection at the corner)

**Comment by Swado** [comment]
@maxim-saplin 
Please checkout below and let me know if changes required.
Without Fixed Columns

- Set color as Amber.
- Set a solid black border around header.
- Applied gradient [amber,red]

![Screenshot 2023-09-07 at 12 28 35 PM](https://github.com/maxim-saplin/data_table_2/assets/64943415/beb905b3-ffd6-49e0-9543-cbf7f781b6c6)

WIth Fixed Columns

- New field headerRowDecoration will take precedence
- fixedCornerColor will be overrided.
- If gradient applied it would be applied separately.

![Screenshot 2023-09-07 at 12 27 11 PM](https://github.com/maxim-saplin/data_table_2/assets/64943415/13e33f43-fafa-4e17-ab50-7aeb31dfbd61)

**Comment by maxim-saplin** [comment]
Yep, #219 is related. Would be great to get your input there as well.

Regarding the heading row, would be great to get a PR so I could look closer.

**Comment by maxim-saplin** [comment]
Speaking of this whole subject of styling, here some remarks/considerations I have:
- Styling can be applied at row, column and cell leveles - different users requested different features
- There're already plenty of styling fields in the class
- There's hovering effects on cell and row levels which get spoiled if widgets get some color overrides and are drawn in the cells
- In flutter there's actove use of material styles, i.e. styles that respond to actions 
- Introducing more features and more interdependencjes can bring more harm than use, most of the users just need simple stuff with low entry point

**Comment by Swado** [comment]
Agreed, simplicity should be maintained.

**Comment by maxim-saplin** [comment]
Pushed to pub.dev
