### ISSUE TITLE
Is there any option to place sort icon on the right side instead of left side of the text

### ISSUE THREAD

**Issue by coolit** [maxim-saplin/data_table_2#73]
Because if text in cell is aligned to center-left and text in head row is also aligned to center-left, then the texts doesn't look aligned well if icon is on the leftside of text. 
Also, the icon should be place tightly close to the column text. But currently if column text is aligned to center, the icon is not that close to the text.

**Comment by maxim-saplin** [comment]
Hello, sort icons are hard-coded. At the moment the fastest way is forking the plugin and making your own changes to the widgets used in headers

**Comment by coolit** [comment]
ok thanks
