### ISSUE TITLE
Can i reduce particular column size.

### ISSUE THREAD

**Issue by Govindbetterlives** [maxim-saplin/data_table_2#76]
Hi sir,
How can i reduce particular column size.
Ex. s.no - Column.S to width 75px

**Comment by maxim-saplin** [comment]
Hi, currently you can only set relative size via ColumnSize (S, M, L) and there's no feature to set absolute values to column widths. There's though a PR with that capability though to finalised yet. You can track fiexed with feature here: https://github.com/maxim-saplin/data_table_2/issues/47
