### ISSUE TITLE
Table with many columns compressing content

### ISSUE THREAD

**Issue by ReniDelonzek** [maxim-saplin/data_table_2#8]
I noticed that you changed the default column width behavior, this behavior is good when you have a few columns, but when there are several columns on a not too wide screen, it causes the text to be expressed, not showing proper behavior.

![image](https://user-images.githubusercontent.com/16869726/120378919-6f005180-c2f5-11eb-9caa-493e9eb0dcf5.png)

I propose a very simple solution that involves wrapping the table in a container with minimum width restrictions

```
Scrollbar(
                    child: SingleChildScrollView(
                        scrollDirection: Axis.horizontal,
                        child: Container(
                          constraints:
                              BoxConstraints(minWidth: constraint.maxWidth),
                          child: ...
```

And stop defining a width for the columns, keeping the default behavior so that they occupy the necessary size according to their content, except when that size is explicitly defined by the constructor

**Comment by maxim-saplin** [comment]
I believe this behavior (if I caught the idea) is already implemented via minWidth property, please see the following issue: https://github.com/maxim-saplin/data_table_2/issues/6

**Comment by ReniDelonzek** [comment]
Not exactly, because with minWidth I need to explicitly define a minimum width (which you are using to determine the width for the columns also with var columnWidth = totalColWidth / columns.length;)
My suggestion is to offer the possibility to keep the default behavior, where the width of columns is automatically defined by their content, and apply a solution like the one I offered in the previous comment, so that the table always occupies AT LEAST the full width available, avoiding empty spaces on the right

**Comment by maxim-saplin** [comment]
OK. The idea of having S, M, L sizes for columns is to avoid calculating sizes of all cells in the first pass and laying out the whole widget in the second pass. Also this approach syncs footer to header dimensions (they are internaly 2 separate Table widgets).
In other words the suggestion you have requires rebuilding the core of the widget which while cam be useful is not reasonable to do.

**Comment by ReniDelonzek** [comment]
I think it might be interesting to offer both ways, but I understand you might not want to support it here. 
If you really have no intention of doing so, I would ask you to provide a license for the library so that I can assess whether I should work on it from a fork of yours or should I build a new one

**Comment by maxim-saplin** [comment]
It's BSD license (you can find the file in the root of sources), forking the repo shouldn't be a problem.

**Comment by ReniDelonzek** [comment]
Right. Thank you for your attention
