### ISSUE TITLE
How to Centered Table Column and Rows Value

### ISSUE THREAD

**Issue by flameblue59** [maxim-saplin/data_table_2#82]
Hi, I do not find anything related to centered data_table_2 column and rows value. Do you know how to achieve this one? Thank you.

**Comment by maxim-saplin** [comment]
You can use `Center() `widget inside `DataCell() `when defining a `DataRow()`, e.g.:

```
      cells: [
        DataCell(Center(child: Text(dessert.name))),
```

Make sure that `DataColumn` corresponding to the call is not set to  `numeric`
