### ISSUE TITLE
Vertical scrollbar not visible when all columns can't fit in screen

### ISSUE THREAD

**Issue by merabtenei** [maxim-saplin/data_table_2#83]
We came across this Widget when searching for a table that can scroll both horizontally and vertically. Unfortunately DataTable2 don't show the vertical scrollbar at the right side when there's too many rows.

We can find the scrollbar after scrolling horizontally all the way to the last column, but I suppose the scrollbar should be visible without scrolling the the end.

![image](https://user-images.githubusercontent.com/95150308/164560286-e19d8f46-8f82-4a92-8683-cf1bc9c01601.png)

![image](https://user-images.githubusercontent.com/95150308/164560367-f1509628-5209-4818-b081-4fe2c926fb31.png)

**Comment by maxim-saplin** [comment]
Thanks for posting the issue. Indeed that's the result of nesting SginleChildScrollView's one inside another, an implementation detail of the widget. I haven't found a quick workaround for that bug, will look latter to see how that can be resolved

**Comment by nosmirck** [comment]
@maxim-saplin this might help:
https://pub.dev/packages/cross_scroll

**Comment by maxim-saplin** [comment]
The fix is already in main branch, will close the issue when the changes are pushed to pub.dev
