### ISSUE TITLE
Sorting arrow behaves in reverse way

### ISSUE THREAD

**Issue by MauroDiamantino** [maxim-saplin/data_table_2#84]
Hello, I'm trying this wonderful widget, but I thing the sorting arrow is behaving in reverse way. I understand that the arrow must point in the direction where the data grow, am I wrong?

**Comment by maxim-saplin** [comment]
Not exactly. Ascending sorting order corresponds to arrows looking up. In that case data grows in opposite direction. That's standard behavior of Flutter's stock widgets and sorting arrows
