### ISSUE TITLE
Horizontal scroll

### ISSUE THREAD

**Issue by tranvanphay** [maxim-saplin/data_table_2#9]
Hi,
It is great library, I found PaginatedDataTable2 in your library source code, i think it is developing. But in current version, it is very helpful for me and I want to know: "Is it support scroll horizontal in current version?"
![image](https://user-images.githubusercontent.com/42576241/120739029-0d213100-c51b-11eb-95dd-d69f21fb0108.png)

**Comment by maxim-saplin** [comment]
Hi. There's minWidth property which enables horizontal scrolling when container of the table shrinks below the value. Is that the behavior you'd like to get?

**Comment by tranvanphay** [comment]
> Hi. There's minWidth property which enables horizontal scrolling when container of the table shrinks below the value. Is that the behavior you'd like to get?

It mean, if have many column it will show horizontal scroll. 
![horizontalscroll](https://user-images.githubusercontent.com/42576241/120741137-b1f13d80-c51e-11eb-8a90-31c6b017e9fc.gif)

**Comment by maxim-saplin** [comment]
The sample you showed has left column fixed - there's no such feature, unfortunately

**Comment by tranvanphay** [comment]
> The sample you showed has left column fixed - there's no such feature, unfortunately

Yes, but I just need horizontal scroll, not need fixed left column

**Comment by maxim-saplin** [comment]
![scrolling](https://user-images.githubusercontent.com/7947027/120853160-e8ad6f00-c583-11eb-97a0-76efe49397af.gif)

- this is the current implementation of horizontal scrolling when maxWidth is set

**Comment by tranvanphay** [comment]
> ![scrolling](https://user-images.githubusercontent.com/7947027/120853160-e8ad6f00-c583-11eb-97a0-76efe49397af.gif)
> 
> * this is the current implementation of horizontal scrolling when minWidth is set

Yes, It worked
Thanks
