### ISSUE TITLE
DataTable2, DataColumn and Row is unusable

### ISSUE THREAD

**Issue by Panca6** [maxim-saplin/data_table_2#90]
![image](https://user-images.githubusercontent.com/83634019/169455531-8e2470a5-6942-43e0-bc51-789760af7aed.png)
i cant use it , they only have 1 property super.

**Comment by maxim-saplin** [comment]
The package has been updated to Dart 2.17.0, try upping your SDK in pubspec.yaml:

https://m.aliexpress.ru/item/4000112103739.html?sku_id=10000000289663621

**Comment by Panca6** [comment]
> The package has been updated to Dart 2.17.0, try upping it in your pubspec.yaml:
> 
> ```
> environment:
>   sdk: ">=2.17.0 <3.0.0"
> ```

tried both 2.17.1 and  2.17.0 same result, 
-pub cache repair 
-clean

**Comment by maxim-saplin** [comment]
Are you on Flutter 3.0?

Please show your flutter doctor output

**Comment by Panca6** [comment]
[✓] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22000.675], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code, 64-bit edition (version 1.67.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by maxim-saplin** [comment]
My other suspect is VSCode showing wrong autocomplete because of a bug on it's side. You've got VSCode version 1.67.1, I have 1.67.2 , beides I've got Dart extension v3.40.0 and Flutter extension also at v3.40.0

**Comment by maxim-saplin** [comment]
Closing the issue, let me know if you have updates
