### ISSUE TITLE
how to get data from datatablesource class?

### ISSUE THREAD

**Issue by harryandroiddev** [maxim-saplin/data_table_2#94]
i have defined the selected list for showing the selecting values inside the datatablesource class, but i am unable to access this list in my main widget class how it is possible?

**Comment by maxim-saplin** [comment]
DataSource implementation is 100% on developer, you're free to create whatever ways to expose and manipulate the data inside datasource. Please check samples:
https://github.com/maxim-saplin/data_table_2/blob/main/example/lib/data_sources.dart
