### ISSUE TITLE
How to navigate to a required page number ?

### ISSUE THREAD

**Issue by bhavyalatha26** [maxim-saplin/data_table_2#95]
Hi @maxim-saplin ,

At the moment using the pagination navigator, we can goto **first, last, previous and next** pages. Is there a way I can go to a desired page by giving the page number.

Something like `datasource.gotoPage(int pageNumber)` kind of function. I checked the **AsyncPaginatedDataTable2**, but could not find anything similar.

Regards,
Bhavya

**Comment by maxim-saplin** [comment]
Hi @bhavyalatha26 ,

In `PaginatorColtroller`  there's a method `goToPageWithRow() `which can be used (you can use rowsPerPage*numebrOfPageRequired). The controller can be attached to AsyncPaginatedDataTable2 or PaginatedDataTablwe2. You can check the **Cutomer Pager** sample: https://maxim-saplin.github.io/data_table_2/#/asyncpaginated2
