### ISSUE TITLE
Delete feature with data table

### ISSUE THREAD

**Issue by chetanclozio** [maxim-saplin/data_table_2#96]
Hi @maxim-saplin Thanks for such a great library and it is easy to integrate with the application. We are having functionality to delete the data row within the data table but no success yet. Can you please guide us on how to acheive the implementation with your library?
Help will save us from falling our commitment.
Thanks,
Chetan

**Comment by maxim-saplin** [comment]
Hi there, sorry late reply, I missed your message... The easiest you can do is have a delete button in the row and a tap handler which will delete the item from the data source and request the widget to rebuild - i.e. via setState() in the StatefulWidget hosting the table
