### ISSUE TITLE
Getting this pesky error after updating to latest version of the package

### ISSUE THREAD

**Issue by fisforfaheem** [maxim-saplin/data_table_2#98]
![image](https://user-images.githubusercontent.com/35878088/172655618-22c6fbcf-6640-4822-8eb4-4d34c20ce460.png)

also geeting a blank screen on table 
![image](https://user-images.githubusercontent.com/35878088/172655685-0d650624-e07c-40e5-b772-1fd928742689.png)

**Comment by maxim-saplin** [comment]
Could you please provide the output of `flutter doctor -v`, the version of the package you have (you can check pubspec.lock) and the target platform you're building your app for

**Comment by maxim-saplin** [comment]
Also a snippet of code how you add DataTable2 and what kind of widgets wrap it is helpful - I suspect there might be some scrollable above the table which messes with the ScingleChildScrollView's used by the widget

**Comment by fisforfaheem** [comment]
more Clear: page 1
![image](https://user-images.githubusercontent.com/35878088/172873621-18feafcb-f99f-4d22-8ad4-111097d17e8d.png)

**Comment by fisforfaheem** [comment]
this is Expercted Result:
![image](https://user-images.githubusercontent.com/35878088/172874983-48449af9-a2f8-4100-83b1-5ed99a217a38.png)

**Comment by maxim-saplin** [comment]
You can't put DataTable2 inside SingleChildScrollView and Column, it won't work. Those parents don't have dimension constraints.

**Comment by fisforfaheem** [comment]
If you may, please remove these from the following file for understanding
https://drive.google.com/drive/folders/1Nwscj8gIjvDT9X6gSgZRdmwB6tf-6RJD?usp=sharing.
.:




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/09/22,
11:59:30 AM

**Comment by fisforfaheem** [comment]
What should be done with the column? i have already removed Singlechildscroll

**Comment by fisforfaheem** [comment]
could you please tell what should be used alternative to column

**Comment by maxim-saplin** [comment]
Either reome column and leave just the table widget OR try putting DataTable2 into Expanded or Flexible

**Comment by fisforfaheem** [comment]
Brother, I am trying but still having the same issue, could you please help a bit, This problem never occured on previous versions though. I am a beginner and dont know much about this...

**Comment by maxim-saplin** [comment]
Try this:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/7947027/173372300-f4a37659-09e7-4a58-9259-feda4653e0d1.png">


Instead of this:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/7947027/173371899-e7b1ae51-6ffc-48cf-bc10-5c36841702df.png">

**Comment by fisforfaheem** [comment]
I changed the code to this:
[image: image.png]

but i stil get this error:
[image: image.png]

**Comment by fisforfaheem** [comment]
i mean could you please highlight what should i remove to fix the issue?
